// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 1717603779;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__proctoring__analyze_acoustic_chunk_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "analyze_acoustic_chunk",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_pcm16_bytes = <Vec<u8>>::sse_decode(&mut deserializer);
            let api_loss_threshold_dbfs = <f64>::sse_decode(&mut deserializer);
            let api_loss_streak = <u32>::sse_decode(&mut deserializer);
            let api_loss_samples_to_trigger = <u32>::sse_decode(&mut deserializer);
            let api_speech_threshold_dbfs = <f64>::sse_decode(&mut deserializer);
            let api_speech_streak = <u32>::sse_decode(&mut deserializer);
            let api_speech_samples_to_trigger = <u32>::sse_decode(&mut deserializer);
            let api_last_speech_strike_at_ms = <i64>::sse_decode(&mut deserializer);
            let api_speech_cooldown_ms = <i64>::sse_decode(&mut deserializer);
            let api_now_ms = <i64>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok =
                    Result::<_, ()>::Ok(crate::api::proctoring::analyze_acoustic_chunk(
                        api_pcm16_bytes,
                        api_loss_threshold_dbfs,
                        api_loss_streak,
                        api_loss_samples_to_trigger,
                        api_speech_threshold_dbfs,
                        api_speech_streak,
                        api_speech_samples_to_trigger,
                        api_last_speech_strike_at_ms,
                        api_speech_cooldown_ms,
                        api_now_ms,
                    ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__proctoring__analyze_environment_frame_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "analyze_environment_frame",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_object_labels = <Vec<String>>::sse_decode(&mut deserializer);
            let api_lighting_score = <f64>::sse_decode(&mut deserializer);
            let api_rotation_covered = <bool>::sse_decode(&mut deserializer);
            let api_forbidden_keywords = <Vec<String>>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok =
                    Result::<_, ()>::Ok(crate::api::proctoring::analyze_environment_frame(
                        api_object_labels,
                        api_lighting_score,
                        api_rotation_covered,
                        api_forbidden_keywords,
                    ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__proctoring__analyze_face_state_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "analyze_face_state",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_face_count = <u32>::sse_decode(&mut deserializer);
            let api_include_gaze = <bool>::sse_decode(&mut deserializer);
            let api_yaw = <f64>::sse_decode(&mut deserializer);
            let api_pitch = <f64>::sse_decode(&mut deserializer);
            let api_now_ms = <i64>::sse_decode(&mut deserializer);
            let api_last_multi_face_strike_at_ms = <i64>::sse_decode(&mut deserializer);
            let api_multi_face_cooldown_ms = <i64>::sse_decode(&mut deserializer);
            let api_gaze_away_started_at_ms = <Option<i64>>::sse_decode(&mut deserializer);
            let api_gaze_away_duration_ms = <i64>::sse_decode(&mut deserializer);
            let api_last_gaze_warning_at_ms = <i64>::sse_decode(&mut deserializer);
            let api_gaze_warning_cooldown_ms = <i64>::sse_decode(&mut deserializer);
            let api_yaw_threshold = <f64>::sse_decode(&mut deserializer);
            let api_pitch_threshold = <f64>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::proctoring::analyze_face_state(
                    api_face_count,
                    api_include_gaze,
                    api_yaw,
                    api_pitch,
                    api_now_ms,
                    api_last_multi_face_strike_at_ms,
                    api_multi_face_cooldown_ms,
                    api_gaze_away_started_at_ms,
                    api_gaze_away_duration_ms,
                    api_last_gaze_warning_at_ms,
                    api_gaze_warning_cooldown_ms,
                    api_yaw_threshold,
                    api_pitch_threshold,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__proctoring__analyze_motion_sample_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "analyze_motion_sample",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_x = <f64>::sse_decode(&mut deserializer);
            let api_y = <f64>::sse_decode(&mut deserializer);
            let api_z = <f64>::sse_decode(&mut deserializer);
            let api_x_threshold = <f64>::sse_decode(&mut deserializer);
            let api_y_threshold = <f64>::sse_decode(&mut deserializer);
            let api_z_threshold = <f64>::sse_decode(&mut deserializer);
            let api_now_ms = <i64>::sse_decode(&mut deserializer);
            let api_last_violation_at_ms = <i64>::sse_decode(&mut deserializer);
            let api_cooldown_ms = <i64>::sse_decode(&mut deserializer);
            let api_window_start_ms = <i64>::sse_decode(&mut deserializer);
            let api_window_ms = <i64>::sse_decode(&mut deserializer);
            let api_burst_count = <u32>::sse_decode(&mut deserializer);
            let api_burst_threshold = <u32>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok =
                    Result::<_, ()>::Ok(crate::api::proctoring::analyze_motion_sample(
                        api_x,
                        api_y,
                        api_z,
                        api_x_threshold,
                        api_y_threshold,
                        api_z_threshold,
                        api_now_ms,
                        api_last_violation_at_ms,
                        api_cooldown_ms,
                        api_window_start_ms,
                        api_window_ms,
                        api_burst_count,
                        api_burst_threshold,
                    ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__proctoring__analyze_scan_frame_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "analyze_scan_frame",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_plane0_bytes = <Vec<u8>>::sse_decode(&mut deserializer);
            let api_width = <u32>::sse_decode(&mut deserializer);
            let api_height = <u32>::sse_decode(&mut deserializer);
            let api_bytes_per_row = <u32>::sse_decode(&mut deserializer);
            let api_pixel_format = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::proctoring::analyze_scan_frame(
                    api_plane0_bytes,
                    api_width,
                    api_height,
                    api_bytes_per_row,
                    api_pixel_format,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__proctoring__clear_vision_model_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "clear_vision_model",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok({
                    crate::api::proctoring::clear_vision_model();
                })?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__proctoring__current_vision_model_status_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "current_vision_model_status",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok =
                    Result::<_, ()>::Ok(crate::api::proctoring::current_vision_model_status())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__proctoring__estimate_lighting_from_luma_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "estimate_lighting_from_luma",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_luma_bytes = <Vec<u8>>::sse_decode(&mut deserializer);
            let api_sample_stride = <u32>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok =
                    Result::<_, ()>::Ok(crate::api::proctoring::estimate_lighting_from_luma(
                        api_luma_bytes,
                        api_sample_stride,
                    ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__proctoring__load_vision_model_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "load_vision_model",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_manifest_json = <String>::sse_decode(&mut deserializer);
            let api_model_bytes = <Vec<u8>>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::proctoring::load_vision_model(
                    api_manifest_json,
                    api_model_bytes,
                ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__proctoring__process_acoustic_sample_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "process_acoustic_sample",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_dbfs = <f64>::sse_decode(&mut deserializer);
            let api_loss_threshold_dbfs = <f64>::sse_decode(&mut deserializer);
            let api_loss_streak = <u32>::sse_decode(&mut deserializer);
            let api_loss_samples_to_trigger = <u32>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok =
                    Result::<_, ()>::Ok(crate::api::proctoring::process_acoustic_sample(
                        api_dbfs,
                        api_loss_threshold_dbfs,
                        api_loss_streak,
                        api_loss_samples_to_trigger,
                    ))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__proctoring__update_rotation_progress_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "update_rotation_progress",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_x = <f64>::sse_decode(&mut deserializer);
            let api_y = <f64>::sse_decode(&mut deserializer);
            let api_z = <f64>::sse_decode(&mut deserializer);
            let api_accumulated = <f64>::sse_decode(&mut deserializer);
            let api_current_progress = <f64>::sse_decode(&mut deserializer);
            let api_delta_scale = <f64>::sse_decode(&mut deserializer);
            let api_min_delta = <f64>::sse_decode(&mut deserializer);
            let api_target_accumulated = <f64>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok =
                    Result::<_, ()>::Ok(crate::api::proctoring::update_rotation_progress(
                        api_x,
                        api_y,
                        api_z,
                        api_accumulated,
                        api_current_progress,
                        api_delta_scale,
                        api_min_delta,
                        api_target_accumulated,
                    ))?;
                Ok(output_ok)
            })())
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::proctoring::AcousticAnalysisDecision {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_dbfs = <f64>::sse_decode(deserializer);
        let mut var_updatedLossStreak = <u32>::sse_decode(deserializer);
        let mut var_shouldTriggerScan = <bool>::sse_decode(deserializer);
        let mut var_normalizedTetherSignal = <f64>::sse_decode(deserializer);
        let mut var_updatedSpeechStreak = <u32>::sse_decode(deserializer);
        let mut var_shouldTriggerSpeech = <bool>::sse_decode(deserializer);
        let mut var_updatedLastSpeechStrikeAtMs = <i64>::sse_decode(deserializer);
        return crate::api::proctoring::AcousticAnalysisDecision {
            dbfs: var_dbfs,
            updated_loss_streak: var_updatedLossStreak,
            should_trigger_scan: var_shouldTriggerScan,
            normalized_tether_signal: var_normalizedTetherSignal,
            updated_speech_streak: var_updatedSpeechStreak,
            should_trigger_speech: var_shouldTriggerSpeech,
            updated_last_speech_strike_at_ms: var_updatedLastSpeechStrikeAtMs,
        };
    }
}

impl SseDecode for crate::api::proctoring::AcousticSampleDecision {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_updatedLossStreak = <u32>::sse_decode(deserializer);
        let mut var_shouldTriggerScan = <bool>::sse_decode(deserializer);
        let mut var_normalizedTetherSignal = <f64>::sse_decode(deserializer);
        return crate::api::proctoring::AcousticSampleDecision {
            updated_loss_streak: var_updatedLossStreak,
            should_trigger_scan: var_shouldTriggerScan,
            normalized_tether_signal: var_normalizedTetherSignal,
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::proctoring::EnvironmentFrameDecision {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_normalizedLightingScore = <f64>::sse_decode(deserializer);
        let mut var_rotationConfirmed = <bool>::sse_decode(deserializer);
        let mut var_forbiddenObjects = <Vec<String>>::sse_decode(deserializer);
        return crate::api::proctoring::EnvironmentFrameDecision {
            normalized_lighting_score: var_normalizedLightingScore,
            rotation_confirmed: var_rotationConfirmed,
            forbidden_objects: var_forbiddenObjects,
        };
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::proctoring::FaceAnalysisDecision {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_shouldFlagMultiFace = <bool>::sse_decode(deserializer);
        let mut var_shouldWarnGaze = <bool>::sse_decode(deserializer);
        let mut var_updatedLastMultiFaceStrikeAtMs = <i64>::sse_decode(deserializer);
        let mut var_updatedLastGazeWarningAtMs = <i64>::sse_decode(deserializer);
        let mut var_updatedGazeAwayStartedAtMs = <Option<i64>>::sse_decode(deserializer);
        return crate::api::proctoring::FaceAnalysisDecision {
            should_flag_multi_face: var_shouldFlagMultiFace,
            should_warn_gaze: var_shouldWarnGaze,
            updated_last_multi_face_strike_at_ms: var_updatedLastMultiFaceStrikeAtMs,
            updated_last_gaze_warning_at_ms: var_updatedLastGazeWarningAtMs,
            updated_gaze_away_started_at_ms: var_updatedGazeAwayStartedAtMs,
        };
    }
}

impl SseDecode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for crate::api::proctoring::MotionAnalysisDecision {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_moved = <bool>::sse_decode(deserializer);
        let mut var_shouldLogViolation = <bool>::sse_decode(deserializer);
        let mut var_shouldTriggerScan = <bool>::sse_decode(deserializer);
        let mut var_updatedLastViolationAtMs = <i64>::sse_decode(deserializer);
        let mut var_updatedWindowStartMs = <i64>::sse_decode(deserializer);
        let mut var_updatedBurstCount = <u32>::sse_decode(deserializer);
        return crate::api::proctoring::MotionAnalysisDecision {
            moved: var_moved,
            should_log_violation: var_shouldLogViolation,
            should_trigger_scan: var_shouldTriggerScan,
            updated_last_violation_at_ms: var_updatedLastViolationAtMs,
            updated_window_start_ms: var_updatedWindowStartMs,
            updated_burst_count: var_updatedBurstCount,
        };
    }
}

impl SseDecode for Option<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<i64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::proctoring::RotationAnalysisDecision {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_updatedAccumulated = <f64>::sse_decode(deserializer);
        let mut var_updatedProgress = <f64>::sse_decode(deserializer);
        let mut var_rotationConfirmed = <bool>::sse_decode(deserializer);
        return crate::api::proctoring::RotationAnalysisDecision {
            updated_accumulated: var_updatedAccumulated,
            updated_progress: var_updatedProgress,
            rotation_confirmed: var_rotationConfirmed,
        };
    }
}

impl SseDecode for crate::api::proctoring::ScanFrameDecision {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_lightingScore = <f64>::sse_decode(deserializer);
        let mut var_objectLabels = <Vec<String>>::sse_decode(deserializer);
        let mut var_faceCount = <u32>::sse_decode(deserializer);
        let mut var_estimatedYaw = <f64>::sse_decode(deserializer);
        let mut var_estimatedPitch = <f64>::sse_decode(deserializer);
        return crate::api::proctoring::ScanFrameDecision {
            lighting_score: var_lightingScore,
            object_labels: var_objectLabels,
            face_count: var_faceCount,
            estimated_yaw: var_estimatedYaw,
            estimated_pitch: var_estimatedPitch,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for crate::api::proctoring::VisionModelStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_loaded = <bool>::sse_decode(deserializer);
        let mut var_modelName = <String>::sse_decode(deserializer);
        let mut var_inputWidth = <u32>::sse_decode(deserializer);
        let mut var_inputHeight = <u32>::sse_decode(deserializer);
        let mut var_confidenceThreshold = <f64>::sse_decode(deserializer);
        let mut var_labelCount = <u32>::sse_decode(deserializer);
        let mut var_message = <String>::sse_decode(deserializer);
        return crate::api::proctoring::VisionModelStatus {
            loaded: var_loaded,
            model_name: var_modelName,
            input_width: var_inputWidth,
            input_height: var_inputHeight,
            confidence_threshold: var_confidenceThreshold,
            label_count: var_labelCount,
            message: var_message,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__proctoring__analyze_acoustic_chunk_impl(ptr, rust_vec_len, data_len),
        2 => wire__crate__api__proctoring__analyze_environment_frame_impl(
            ptr,
            rust_vec_len,
            data_len,
        ),
        3 => wire__crate__api__proctoring__analyze_face_state_impl(ptr, rust_vec_len, data_len),
        4 => wire__crate__api__proctoring__analyze_motion_sample_impl(ptr, rust_vec_len, data_len),
        5 => wire__crate__api__proctoring__analyze_scan_frame_impl(ptr, rust_vec_len, data_len),
        6 => wire__crate__api__proctoring__clear_vision_model_impl(ptr, rust_vec_len, data_len),
        7 => wire__crate__api__proctoring__current_vision_model_status_impl(
            ptr,
            rust_vec_len,
            data_len,
        ),
        8 => wire__crate__api__proctoring__estimate_lighting_from_luma_impl(
            ptr,
            rust_vec_len,
            data_len,
        ),
        9 => wire__crate__api__proctoring__load_vision_model_impl(ptr, rust_vec_len, data_len),
        10 => {
            wire__crate__api__proctoring__process_acoustic_sample_impl(ptr, rust_vec_len, data_len)
        }
        11 => {
            wire__crate__api__proctoring__update_rotation_progress_impl(ptr, rust_vec_len, data_len)
        }
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::proctoring::AcousticAnalysisDecision {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.dbfs.into_into_dart().into_dart(),
            self.updated_loss_streak.into_into_dart().into_dart(),
            self.should_trigger_scan.into_into_dart().into_dart(),
            self.normalized_tether_signal.into_into_dart().into_dart(),
            self.updated_speech_streak.into_into_dart().into_dart(),
            self.should_trigger_speech.into_into_dart().into_dart(),
            self.updated_last_speech_strike_at_ms
                .into_into_dart()
                .into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::proctoring::AcousticAnalysisDecision
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::proctoring::AcousticAnalysisDecision>
    for crate::api::proctoring::AcousticAnalysisDecision
{
    fn into_into_dart(self) -> crate::api::proctoring::AcousticAnalysisDecision {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::proctoring::AcousticSampleDecision {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.updated_loss_streak.into_into_dart().into_dart(),
            self.should_trigger_scan.into_into_dart().into_dart(),
            self.normalized_tether_signal.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::proctoring::AcousticSampleDecision
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::proctoring::AcousticSampleDecision>
    for crate::api::proctoring::AcousticSampleDecision
{
    fn into_into_dart(self) -> crate::api::proctoring::AcousticSampleDecision {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::proctoring::EnvironmentFrameDecision {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.normalized_lighting_score.into_into_dart().into_dart(),
            self.rotation_confirmed.into_into_dart().into_dart(),
            self.forbidden_objects.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::proctoring::EnvironmentFrameDecision
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::proctoring::EnvironmentFrameDecision>
    for crate::api::proctoring::EnvironmentFrameDecision
{
    fn into_into_dart(self) -> crate::api::proctoring::EnvironmentFrameDecision {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::proctoring::FaceAnalysisDecision {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.should_flag_multi_face.into_into_dart().into_dart(),
            self.should_warn_gaze.into_into_dart().into_dart(),
            self.updated_last_multi_face_strike_at_ms
                .into_into_dart()
                .into_dart(),
            self.updated_last_gaze_warning_at_ms
                .into_into_dart()
                .into_dart(),
            self.updated_gaze_away_started_at_ms
                .into_into_dart()
                .into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::proctoring::FaceAnalysisDecision
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::proctoring::FaceAnalysisDecision>
    for crate::api::proctoring::FaceAnalysisDecision
{
    fn into_into_dart(self) -> crate::api::proctoring::FaceAnalysisDecision {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::proctoring::MotionAnalysisDecision {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.moved.into_into_dart().into_dart(),
            self.should_log_violation.into_into_dart().into_dart(),
            self.should_trigger_scan.into_into_dart().into_dart(),
            self.updated_last_violation_at_ms
                .into_into_dart()
                .into_dart(),
            self.updated_window_start_ms.into_into_dart().into_dart(),
            self.updated_burst_count.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::proctoring::MotionAnalysisDecision
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::proctoring::MotionAnalysisDecision>
    for crate::api::proctoring::MotionAnalysisDecision
{
    fn into_into_dart(self) -> crate::api::proctoring::MotionAnalysisDecision {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::proctoring::RotationAnalysisDecision {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.updated_accumulated.into_into_dart().into_dart(),
            self.updated_progress.into_into_dart().into_dart(),
            self.rotation_confirmed.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::proctoring::RotationAnalysisDecision
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::proctoring::RotationAnalysisDecision>
    for crate::api::proctoring::RotationAnalysisDecision
{
    fn into_into_dart(self) -> crate::api::proctoring::RotationAnalysisDecision {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::proctoring::ScanFrameDecision {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.lighting_score.into_into_dart().into_dart(),
            self.object_labels.into_into_dart().into_dart(),
            self.face_count.into_into_dart().into_dart(),
            self.estimated_yaw.into_into_dart().into_dart(),
            self.estimated_pitch.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::proctoring::ScanFrameDecision
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::proctoring::ScanFrameDecision>
    for crate::api::proctoring::ScanFrameDecision
{
    fn into_into_dart(self) -> crate::api::proctoring::ScanFrameDecision {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::proctoring::VisionModelStatus {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.loaded.into_into_dart().into_dart(),
            self.model_name.into_into_dart().into_dart(),
            self.input_width.into_into_dart().into_dart(),
            self.input_height.into_into_dart().into_dart(),
            self.confidence_threshold.into_into_dart().into_dart(),
            self.label_count.into_into_dart().into_dart(),
            self.message.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::proctoring::VisionModelStatus
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::proctoring::VisionModelStatus>
    for crate::api::proctoring::VisionModelStatus
{
    fn into_into_dart(self) -> crate::api::proctoring::VisionModelStatus {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::proctoring::AcousticAnalysisDecision {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f64>::sse_encode(self.dbfs, serializer);
        <u32>::sse_encode(self.updated_loss_streak, serializer);
        <bool>::sse_encode(self.should_trigger_scan, serializer);
        <f64>::sse_encode(self.normalized_tether_signal, serializer);
        <u32>::sse_encode(self.updated_speech_streak, serializer);
        <bool>::sse_encode(self.should_trigger_speech, serializer);
        <i64>::sse_encode(self.updated_last_speech_strike_at_ms, serializer);
    }
}

impl SseEncode for crate::api::proctoring::AcousticSampleDecision {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.updated_loss_streak, serializer);
        <bool>::sse_encode(self.should_trigger_scan, serializer);
        <f64>::sse_encode(self.normalized_tether_signal, serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::proctoring::EnvironmentFrameDecision {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f64>::sse_encode(self.normalized_lighting_score, serializer);
        <bool>::sse_encode(self.rotation_confirmed, serializer);
        <Vec<String>>::sse_encode(self.forbidden_objects, serializer);
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::proctoring::FaceAnalysisDecision {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.should_flag_multi_face, serializer);
        <bool>::sse_encode(self.should_warn_gaze, serializer);
        <i64>::sse_encode(self.updated_last_multi_face_strike_at_ms, serializer);
        <i64>::sse_encode(self.updated_last_gaze_warning_at_ms, serializer);
        <Option<i64>>::sse_encode(self.updated_gaze_away_started_at_ms, serializer);
    }
}

impl SseEncode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for crate::api::proctoring::MotionAnalysisDecision {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.moved, serializer);
        <bool>::sse_encode(self.should_log_violation, serializer);
        <bool>::sse_encode(self.should_trigger_scan, serializer);
        <i64>::sse_encode(self.updated_last_violation_at_ms, serializer);
        <i64>::sse_encode(self.updated_window_start_ms, serializer);
        <u32>::sse_encode(self.updated_burst_count, serializer);
    }
}

impl SseEncode for Option<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <i64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::proctoring::RotationAnalysisDecision {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f64>::sse_encode(self.updated_accumulated, serializer);
        <f64>::sse_encode(self.updated_progress, serializer);
        <bool>::sse_encode(self.rotation_confirmed, serializer);
    }
}

impl SseEncode for crate::api::proctoring::ScanFrameDecision {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f64>::sse_encode(self.lighting_score, serializer);
        <Vec<String>>::sse_encode(self.object_labels, serializer);
        <u32>::sse_encode(self.face_count, serializer);
        <f64>::sse_encode(self.estimated_yaw, serializer);
        <f64>::sse_encode(self.estimated_pitch, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for crate::api::proctoring::VisionModelStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.loaded, serializer);
        <String>::sse_encode(self.model_name, serializer);
        <u32>::sse_encode(self.input_width, serializer);
        <u32>::sse_encode(self.input_height, serializer);
        <f64>::sse_encode(self.confidence_threshold, serializer);
        <u32>::sse_encode(self.label_count, serializer);
        <String>::sse_encode(self.message, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
