// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Rust is the final authority for every action proposed by the Python runtime.
/// Unknown or high-impact actions are denied by default.
AiActionAuthorization authorizeAiAction({
  required String action,
  required bool examActive,
}) => BrainCoreApi.instance.api.crateApiAiActionPolicyAuthorizeAiAction(
  action: action,
  examActive: examActive,
);

class AiActionAuthorization {
  final String action;
  final bool allowed;
  final bool requiresUserConsent;
  final String reason;

  const AiActionAuthorization({
    required this.action,
    required this.allowed,
    required this.requiresUserConsent,
    required this.reason,
  });

  @override
  int get hashCode =>
      action.hashCode ^
      allowed.hashCode ^
      requiresUserConsent.hashCode ^
      reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AiActionAuthorization &&
          runtimeType == other.runtimeType &&
          action == other.action &&
          allowed == other.allowed &&
          requiresUserConsent == other.requiresUserConsent &&
          reason == other.reason;
}
