// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

AirBoardActivitySummary analyzeAirBoardContext({
  required AirBoardContext context,
}) => BrainCoreApi.instance.api.crateApiAirBoardAnalyzeAirBoardContext(
  context: context,
);

String buildAirBoardEvidenceManifest({
  required String sessionId,
  required String attemptId,
  required AirBoardActivitySummary summary,
}) => BrainCoreApi.instance.api.crateApiAirBoardBuildAirBoardEvidenceManifest(
  sessionId: sessionId,
  attemptId: attemptId,
  summary: summary,
);

class AirBoardActivitySummary {
  final bool active;
  final bool currentlyWriting;
  final int strokeCount;
  final int pageCount;
  final int activePageIndex;
  final int totalPoints;
  final PlatformInt64 activeDurationMs;
  final PlatformInt64 idleDurationMs;
  final String attentionLevel;
  final String reason;

  const AirBoardActivitySummary({
    required this.active,
    required this.currentlyWriting,
    required this.strokeCount,
    required this.pageCount,
    required this.activePageIndex,
    required this.totalPoints,
    required this.activeDurationMs,
    required this.idleDurationMs,
    required this.attentionLevel,
    required this.reason,
  });

  @override
  int get hashCode =>
      active.hashCode ^
      currentlyWriting.hashCode ^
      strokeCount.hashCode ^
      pageCount.hashCode ^
      activePageIndex.hashCode ^
      totalPoints.hashCode ^
      activeDurationMs.hashCode ^
      idleDurationMs.hashCode ^
      attentionLevel.hashCode ^
      reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AirBoardActivitySummary &&
          runtimeType == other.runtimeType &&
          active == other.active &&
          currentlyWriting == other.currentlyWriting &&
          strokeCount == other.strokeCount &&
          pageCount == other.pageCount &&
          activePageIndex == other.activePageIndex &&
          totalPoints == other.totalPoints &&
          activeDurationMs == other.activeDurationMs &&
          idleDurationMs == other.idleDurationMs &&
          attentionLevel == other.attentionLevel &&
          reason == other.reason;
}

class AirBoardContext {
  final bool isOpen;
  final int activePageIndex;
  final int pageCount;
  final List<AirBoardStroke> strokes;
  final PlatformInt64 lastActivityAtMs;
  final PlatformInt64 openedAtMs;
  final PlatformInt64 nowMs;

  const AirBoardContext({
    required this.isOpen,
    required this.activePageIndex,
    required this.pageCount,
    required this.strokes,
    required this.lastActivityAtMs,
    required this.openedAtMs,
    required this.nowMs,
  });

  @override
  int get hashCode =>
      isOpen.hashCode ^
      activePageIndex.hashCode ^
      pageCount.hashCode ^
      strokes.hashCode ^
      lastActivityAtMs.hashCode ^
      openedAtMs.hashCode ^
      nowMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AirBoardContext &&
          runtimeType == other.runtimeType &&
          isOpen == other.isOpen &&
          activePageIndex == other.activePageIndex &&
          pageCount == other.pageCount &&
          strokes == other.strokes &&
          lastActivityAtMs == other.lastActivityAtMs &&
          openedAtMs == other.openedAtMs &&
          nowMs == other.nowMs;
}

class AirBoardStroke {
  final String strokeId;
  final int pageIndex;
  final String tool;
  final List<AirBoardStrokePoint> points;
  final PlatformInt64 startedAtMs;
  final PlatformInt64 endedAtMs;

  const AirBoardStroke({
    required this.strokeId,
    required this.pageIndex,
    required this.tool,
    required this.points,
    required this.startedAtMs,
    required this.endedAtMs,
  });

  @override
  int get hashCode =>
      strokeId.hashCode ^
      pageIndex.hashCode ^
      tool.hashCode ^
      points.hashCode ^
      startedAtMs.hashCode ^
      endedAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AirBoardStroke &&
          runtimeType == other.runtimeType &&
          strokeId == other.strokeId &&
          pageIndex == other.pageIndex &&
          tool == other.tool &&
          points == other.points &&
          startedAtMs == other.startedAtMs &&
          endedAtMs == other.endedAtMs;
}

class AirBoardStrokePoint {
  final double x;
  final double y;
  final double pressure;
  final PlatformInt64 timestampMs;

  const AirBoardStrokePoint({
    required this.x,
    required this.y,
    required this.pressure,
    required this.timestampMs,
  });

  @override
  int get hashCode =>
      x.hashCode ^ y.hashCode ^ pressure.hashCode ^ timestampMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AirBoardStrokePoint &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          pressure == other.pressure &&
          timestampMs == other.timestampMs;
}
