// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `constant_time_eq`, `sha256_hex`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

String attemptChecksum({required String payloadJson}) => BrainCoreApi
    .instance
    .api
    .crateApiAttemptRecoveryAttemptChecksum(payloadJson: payloadJson);

NativeAttemptRecoveryCheck verifyAttemptSnapshot({
  required String payloadJson,
  required String checksum,
  required String recoveredFrom,
}) => BrainCoreApi.instance.api.crateApiAttemptRecoveryVerifyAttemptSnapshot(
  payloadJson: payloadJson,
  checksum: checksum,
  recoveredFrom: recoveredFrom,
);

class NativeAttemptRecoveryCheck {
  final String checksum;
  final bool checksumValid;
  final String payloadJson;
  final String recoveredFrom;

  const NativeAttemptRecoveryCheck({
    required this.checksum,
    required this.checksumValid,
    required this.payloadJson,
    required this.recoveredFrom,
  });

  @override
  int get hashCode =>
      checksum.hashCode ^
      checksumValid.hashCode ^
      payloadJson.hashCode ^
      recoveredFrom.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeAttemptRecoveryCheck &&
          runtimeType == other.runtimeType &&
          checksum == other.checksum &&
          checksumValid == other.checksumValid &&
          payloadJson == other.payloadJson &&
          recoveredFrom == other.recoveredFrom;
}
