// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `analyse_pcm16`, `decode_pcm16`, `make_fingerprint`, `quantize`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

NativeAudioIntelligenceResult? analyzeAudioPcm16({
  required List<int> bytes,
  required int sampleRate,
  String? previousFingerprint,
}) => BrainCoreApi.instance.api.crateApiAudioIntelligenceAnalyzeAudioPcm16(
  bytes: bytes,
  sampleRate: sampleRate,
  previousFingerprint: previousFingerprint,
);

class NativeAudioIntelligenceResult {
  final bool ready;
  final String label;
  final double rms;
  final double peak;
  final double zeroCrossingRate;
  final double dynamicVariation;
  final double voiceConfidence;
  final bool nearVoiceLikely;
  final bool possibleFarVoiceLikely;
  final bool allowedAmbientLikely;
  final bool repeatedFingerprint;
  final String fingerprint;

  const NativeAudioIntelligenceResult({
    required this.ready,
    required this.label,
    required this.rms,
    required this.peak,
    required this.zeroCrossingRate,
    required this.dynamicVariation,
    required this.voiceConfidence,
    required this.nearVoiceLikely,
    required this.possibleFarVoiceLikely,
    required this.allowedAmbientLikely,
    required this.repeatedFingerprint,
    required this.fingerprint,
  });

  @override
  int get hashCode =>
      ready.hashCode ^
      label.hashCode ^
      rms.hashCode ^
      peak.hashCode ^
      zeroCrossingRate.hashCode ^
      dynamicVariation.hashCode ^
      voiceConfidence.hashCode ^
      nearVoiceLikely.hashCode ^
      possibleFarVoiceLikely.hashCode ^
      allowedAmbientLikely.hashCode ^
      repeatedFingerprint.hashCode ^
      fingerprint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeAudioIntelligenceResult &&
          runtimeType == other.runtimeType &&
          ready == other.ready &&
          label == other.label &&
          rms == other.rms &&
          peak == other.peak &&
          zeroCrossingRate == other.zeroCrossingRate &&
          dynamicVariation == other.dynamicVariation &&
          voiceConfidence == other.voiceConfidence &&
          nearVoiceLikely == other.nearVoiceLikely &&
          possibleFarVoiceLikely == other.possibleFarVoiceLikely &&
          allowedAmbientLikely == other.allowedAmbientLikely &&
          repeatedFingerprint == other.repeatedFingerprint &&
          fingerprint == other.fingerprint;
}
