// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `append_manifest`, `empty_bundle`, `evidence_directory`, `now_millis`, `safe_name`, `sha256_hex`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EvidenceVaultBundle`, `EvidenceVaultRecord`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

String evidenceSha256Hex({required List<int> bytes}) => BrainCoreApi
    .instance
    .api
    .crateApiEvidenceVaultEvidenceSha256Hex(bytes: bytes);

String saveEvidenceBytes({
  required String baseDir,
  required String studentId,
  required String examId,
  required String attemptId,
  required String eventType,
  required String fileType,
  required String reviewReason,
  required List<int> bytes,
  required String metadataJson,
}) => BrainCoreApi.instance.api.crateApiEvidenceVaultSaveEvidenceBytes(
  baseDir: baseDir,
  studentId: studentId,
  examId: examId,
  attemptId: attemptId,
  eventType: eventType,
  fileType: fileType,
  reviewReason: reviewReason,
  bytes: bytes,
  metadataJson: metadataJson,
);

String readEvidenceBundle({
  required String baseDir,
  required String studentId,
  required String examId,
  required String attemptId,
}) => BrainCoreApi.instance.api.crateApiEvidenceVaultReadEvidenceBundle(
  baseDir: baseDir,
  studentId: studentId,
  examId: examId,
  attemptId: attemptId,
);
