// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'air_board.dart';
import 'gaze_calibration.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `strongest_attention_level`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

ExamBehaviourDecision analyzeExamBehaviourContext({
  required ExamBehaviourContext context,
}) => BrainCoreApi.instance.api.crateApiExamBehaviorAnalyzeExamBehaviourContext(
  context: context,
);

class ExamBehaviourContext {
  final GazeZonePrediction gaze;
  final AirBoardActivitySummary airBoard;
  final String headPoseAttentionLevel;
  final String audioAttentionLevel;
  final String screenAttentionLevel;
  final bool externalVoiceDetected;
  final bool screenLeft;
  final PlatformInt64 nowMs;

  const ExamBehaviourContext({
    required this.gaze,
    required this.airBoard,
    required this.headPoseAttentionLevel,
    required this.audioAttentionLevel,
    required this.screenAttentionLevel,
    required this.externalVoiceDetected,
    required this.screenLeft,
    required this.nowMs,
  });

  @override
  int get hashCode =>
      gaze.hashCode ^
      airBoard.hashCode ^
      headPoseAttentionLevel.hashCode ^
      audioAttentionLevel.hashCode ^
      screenAttentionLevel.hashCode ^
      externalVoiceDetected.hashCode ^
      screenLeft.hashCode ^
      nowMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExamBehaviourContext &&
          runtimeType == other.runtimeType &&
          gaze == other.gaze &&
          airBoard == other.airBoard &&
          headPoseAttentionLevel == other.headPoseAttentionLevel &&
          audioAttentionLevel == other.audioAttentionLevel &&
          screenAttentionLevel == other.screenAttentionLevel &&
          externalVoiceDetected == other.externalVoiceDetected &&
          screenLeft == other.screenLeft &&
          nowMs == other.nowMs;
}

class ExamBehaviourDecision {
  final String behaviourLabel;
  final String attentionLevel;
  final bool normalCalculationBehaviour;
  final bool reviewRequired;
  final String suggestedStudentMessage;
  final String reviewerSummary;

  const ExamBehaviourDecision({
    required this.behaviourLabel,
    required this.attentionLevel,
    required this.normalCalculationBehaviour,
    required this.reviewRequired,
    required this.suggestedStudentMessage,
    required this.reviewerSummary,
  });

  @override
  int get hashCode =>
      behaviourLabel.hashCode ^
      attentionLevel.hashCode ^
      normalCalculationBehaviour.hashCode ^
      reviewRequired.hashCode ^
      suggestedStudentMessage.hashCode ^
      reviewerSummary.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExamBehaviourDecision &&
          runtimeType == other.runtimeType &&
          behaviourLabel == other.behaviourLabel &&
          attentionLevel == other.attentionLevel &&
          normalCalculationBehaviour == other.normalCalculationBehaviour &&
          reviewRequired == other.reviewRequired &&
          suggestedStudentMessage == other.suggestedStudentMessage &&
          reviewerSummary == other.reviewerSummary;
}
