// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

EyeIntelligenceResult analyzeEyeRegionSignal({
  required EyeRegionSignal signal,
}) => BrainCoreApi.instance.api.crateApiEyeIntelligenceAnalyzeEyeRegionSignal(
  signal: signal,
);

String describeEyeZoneForStudent({required String zone}) => BrainCoreApi
    .instance
    .api
    .crateApiEyeIntelligenceDescribeEyeZoneForStudent(zone: zone);

class EyeIntelligenceResult {
  final bool usable;
  final double eyeX;
  final double eyeY;
  final double opennessScore;
  final double signalConfidence;
  final bool headStable;
  final String attentionLevel;
  final String reason;

  const EyeIntelligenceResult({
    required this.usable,
    required this.eyeX,
    required this.eyeY,
    required this.opennessScore,
    required this.signalConfidence,
    required this.headStable,
    required this.attentionLevel,
    required this.reason,
  });

  @override
  int get hashCode =>
      usable.hashCode ^
      eyeX.hashCode ^
      eyeY.hashCode ^
      opennessScore.hashCode ^
      signalConfidence.hashCode ^
      headStable.hashCode ^
      attentionLevel.hashCode ^
      reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EyeIntelligenceResult &&
          runtimeType == other.runtimeType &&
          usable == other.usable &&
          eyeX == other.eyeX &&
          eyeY == other.eyeY &&
          opennessScore == other.opennessScore &&
          signalConfidence == other.signalConfidence &&
          headStable == other.headStable &&
          attentionLevel == other.attentionLevel &&
          reason == other.reason;
}

class EyeRegionSignal {
  final double leftEyeOpen;
  final double rightEyeOpen;
  final double leftIrisX;
  final double leftIrisY;
  final double rightIrisX;
  final double rightIrisY;
  final double faceConfidence;
  final double landmarkConfidence;
  final double frameBrightness;
  final double headYaw;
  final double headPitch;
  final double headRoll;

  const EyeRegionSignal({
    required this.leftEyeOpen,
    required this.rightEyeOpen,
    required this.leftIrisX,
    required this.leftIrisY,
    required this.rightIrisX,
    required this.rightIrisY,
    required this.faceConfidence,
    required this.landmarkConfidence,
    required this.frameBrightness,
    required this.headYaw,
    required this.headPitch,
    required this.headRoll,
  });

  @override
  int get hashCode =>
      leftEyeOpen.hashCode ^
      rightEyeOpen.hashCode ^
      leftIrisX.hashCode ^
      leftIrisY.hashCode ^
      rightIrisX.hashCode ^
      rightIrisY.hashCode ^
      faceConfidence.hashCode ^
      landmarkConfidence.hashCode ^
      frameBrightness.hashCode ^
      headYaw.hashCode ^
      headPitch.hashCode ^
      headRoll.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EyeRegionSignal &&
          runtimeType == other.runtimeType &&
          leftEyeOpen == other.leftEyeOpen &&
          rightEyeOpen == other.rightEyeOpen &&
          leftIrisX == other.leftIrisX &&
          leftIrisY == other.leftIrisY &&
          rightIrisX == other.rightIrisX &&
          rightIrisY == other.rightIrisY &&
          faceConfidence == other.faceConfidence &&
          landmarkConfidence == other.landmarkConfidence &&
          frameBrightness == other.frameBrightness &&
          headYaw == other.headYaw &&
          headPitch == other.headPitch &&
          headRoll == other.headRoll;
}
