// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `hex_digest`, `invalid_status`, `normalize`, `template_digest`, `uncertain`, `validate_identity_fields`, `validate_template`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PortableFaceTemplate`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

String buildPortableFaceTemplate({
  required String studentId,
  required String enrollmentId,
  required String modelId,
  required String modelSha256,
  required String preprocessingVersion,
  required List<Float32List> embeddings,
  required double qualityScore,
  required PlatformInt64 createdAtMs,
  required PlatformInt64 expiresAtMs,
}) =>
    BrainCoreApi.instance.api.crateApiFaceVerificationBuildPortableFaceTemplate(
      studentId: studentId,
      enrollmentId: enrollmentId,
      modelId: modelId,
      modelSha256: modelSha256,
      preprocessingVersion: preprocessingVersion,
      embeddings: embeddings,
      qualityScore: qualityScore,
      createdAtMs: createdAtMs,
      expiresAtMs: expiresAtMs,
    );

FaceTemplateStatus validatePortableFaceTemplate({
  required String templateJson,
  required String expectedStudentId,
  required String expectedModelId,
  required String expectedModelSha256,
  required PlatformInt64 nowMs,
}) => BrainCoreApi.instance.api
    .crateApiFaceVerificationValidatePortableFaceTemplate(
      templateJson: templateJson,
      expectedStudentId: expectedStudentId,
      expectedModelId: expectedModelId,
      expectedModelSha256: expectedModelSha256,
      nowMs: nowMs,
    );

FaceVerificationResult verifyFaceEmbedding1To1({
  required String templateJson,
  required List<double> probeEmbedding,
  required double signalQuality,
  required double matchThreshold,
  required PlatformInt64 nowMs,
}) => BrainCoreApi.instance.api.crateApiFaceVerificationVerifyFaceEmbedding1To1(
  templateJson: templateJson,
  probeEmbedding: probeEmbedding,
  signalQuality: signalQuality,
  matchThreshold: matchThreshold,
  nowMs: nowMs,
);

class FaceTemplateStatus {
  final bool valid;
  final String studentId;
  final String enrollmentId;
  final String modelId;
  final String modelSha256;
  final int embeddingDimension;
  final int sampleCount;
  final double qualityScore;
  final String templateSha256;
  final String reason;

  const FaceTemplateStatus({
    required this.valid,
    required this.studentId,
    required this.enrollmentId,
    required this.modelId,
    required this.modelSha256,
    required this.embeddingDimension,
    required this.sampleCount,
    required this.qualityScore,
    required this.templateSha256,
    required this.reason,
  });

  @override
  int get hashCode =>
      valid.hashCode ^
      studentId.hashCode ^
      enrollmentId.hashCode ^
      modelId.hashCode ^
      modelSha256.hashCode ^
      embeddingDimension.hashCode ^
      sampleCount.hashCode ^
      qualityScore.hashCode ^
      templateSha256.hashCode ^
      reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FaceTemplateStatus &&
          runtimeType == other.runtimeType &&
          valid == other.valid &&
          studentId == other.studentId &&
          enrollmentId == other.enrollmentId &&
          modelId == other.modelId &&
          modelSha256 == other.modelSha256 &&
          embeddingDimension == other.embeddingDimension &&
          sampleCount == other.sampleCount &&
          qualityScore == other.qualityScore &&
          templateSha256 == other.templateSha256 &&
          reason == other.reason;
}

class FaceVerificationResult {
  final String state;
  final double similarity;
  final double threshold;
  final double signalQuality;
  final bool reliable;
  final String reason;

  const FaceVerificationResult({
    required this.state,
    required this.similarity,
    required this.threshold,
    required this.signalQuality,
    required this.reliable,
    required this.reason,
  });

  @override
  int get hashCode =>
      state.hashCode ^
      similarity.hashCode ^
      threshold.hashCode ^
      signalQuality.hashCode ^
      reliable.hashCode ^
      reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FaceVerificationResult &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          similarity == other.similarity &&
          threshold == other.threshold &&
          signalQuality == other.signalQuality &&
          reliable == other.reliable &&
          reason == other.reason;
}
