// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `unique_zones`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

GazeCalibrationProfile buildGazeCalibrationProfile({
  required List<GazeCalibrationSample> samples,
}) => BrainCoreApi.instance.api
    .crateApiGazeCalibrationBuildGazeCalibrationProfile(samples: samples);

GazeZonePrediction predictCalibratedGazeZone({
  required GazeCalibrationProfile profile,
  required double eyeX,
  required double eyeY,
  required double headYaw,
  required double headPitch,
  required double signalConfidence,
}) =>
    BrainCoreApi.instance.api.crateApiGazeCalibrationPredictCalibratedGazeZone(
      profile: profile,
      eyeX: eyeX,
      eyeY: eyeY,
      headYaw: headYaw,
      headPitch: headPitch,
      signalConfidence: signalConfidence,
    );

class GazeCalibrationProfile {
  final bool usable;
  final int sampleCount;
  final List<String> zones;
  final double centerEyeX;
  final double centerEyeY;
  final double yawBias;
  final double pitchBias;
  final double qualityScore;
  final String reason;

  const GazeCalibrationProfile({
    required this.usable,
    required this.sampleCount,
    required this.zones,
    required this.centerEyeX,
    required this.centerEyeY,
    required this.yawBias,
    required this.pitchBias,
    required this.qualityScore,
    required this.reason,
  });

  @override
  int get hashCode =>
      usable.hashCode ^
      sampleCount.hashCode ^
      zones.hashCode ^
      centerEyeX.hashCode ^
      centerEyeY.hashCode ^
      yawBias.hashCode ^
      pitchBias.hashCode ^
      qualityScore.hashCode ^
      reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GazeCalibrationProfile &&
          runtimeType == other.runtimeType &&
          usable == other.usable &&
          sampleCount == other.sampleCount &&
          zones == other.zones &&
          centerEyeX == other.centerEyeX &&
          centerEyeY == other.centerEyeY &&
          yawBias == other.yawBias &&
          pitchBias == other.pitchBias &&
          qualityScore == other.qualityScore &&
          reason == other.reason;
}

class GazeCalibrationSample {
  final String zone;
  final double eyeX;
  final double eyeY;
  final double headYaw;
  final double headPitch;
  final double headRoll;
  final double confidence;
  final PlatformInt64 timestampMs;

  const GazeCalibrationSample({
    required this.zone,
    required this.eyeX,
    required this.eyeY,
    required this.headYaw,
    required this.headPitch,
    required this.headRoll,
    required this.confidence,
    required this.timestampMs,
  });

  @override
  int get hashCode =>
      zone.hashCode ^
      eyeX.hashCode ^
      eyeY.hashCode ^
      headYaw.hashCode ^
      headPitch.hashCode ^
      headRoll.hashCode ^
      confidence.hashCode ^
      timestampMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GazeCalibrationSample &&
          runtimeType == other.runtimeType &&
          zone == other.zone &&
          eyeX == other.eyeX &&
          eyeY == other.eyeY &&
          headYaw == other.headYaw &&
          headPitch == other.headPitch &&
          headRoll == other.headRoll &&
          confidence == other.confidence &&
          timestampMs == other.timestampMs;
}

class GazeZonePrediction {
  final String zone;
  final double confidence;
  final bool calibrated;
  final String attentionLevel;
  final String reason;

  const GazeZonePrediction({
    required this.zone,
    required this.confidence,
    required this.calibrated,
    required this.attentionLevel,
    required this.reason,
  });

  @override
  int get hashCode =>
      zone.hashCode ^
      confidence.hashCode ^
      calibrated.hashCode ^
      attentionLevel.hashCode ^
      reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GazeZonePrediction &&
          runtimeType == other.runtimeType &&
          zone == other.zone &&
          confidence == other.confidence &&
          calibrated == other.calibrated &&
          attentionLevel == other.attentionLevel &&
          reason == other.reason;
}
