// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'hand_air_board.dart';
import 'native_vision.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `empty_result`, `normalize_coordinate`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

HandVisionResult reviewHandModelOutput({
  required List<double> output,
  required int numPredictions,
  required int numClasses,
  required int imageWidth,
  required int imageHeight,
  required double confidenceThreshold,
  required double iouThreshold,
  required String layout,
  required List<String> classNames,
  required HandVisionZones zones,
  required PlatformInt64 timestampMs,
}) => BrainCoreApi.instance.api.crateApiHandVisionReviewHandModelOutput(
  output: output,
  numPredictions: numPredictions,
  numClasses: numClasses,
  imageWidth: imageWidth,
  imageHeight: imageHeight,
  confidenceThreshold: confidenceThreshold,
  iouThreshold: iouThreshold,
  layout: layout,
  classNames: classNames,
  zones: zones,
  timestampMs: timestampMs,
);

HandVisionResult reviewHandDetections({
  required List<NativeVisionDetection> detections,
  required int imageWidth,
  required int imageHeight,
  required HandVisionZones zones,
  required PlatformInt64 timestampMs,
}) => BrainCoreApi.instance.api.crateApiHandVisionReviewHandDetections(
  detections: detections,
  imageWidth: imageWidth,
  imageHeight: imageHeight,
  zones: zones,
  timestampMs: timestampMs,
);

class HandVisionResult {
  final HandRegionSignal signal;
  final List<NativeVisionDetection> detections;
  final bool usable;
  final String attentionLevel;
  final String reason;

  const HandVisionResult({
    required this.signal,
    required this.detections,
    required this.usable,
    required this.attentionLevel,
    required this.reason,
  });

  @override
  int get hashCode =>
      signal.hashCode ^
      detections.hashCode ^
      usable.hashCode ^
      attentionLevel.hashCode ^
      reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HandVisionResult &&
          runtimeType == other.runtimeType &&
          signal == other.signal &&
          detections == other.detections &&
          usable == other.usable &&
          attentionLevel == other.attentionLevel &&
          reason == other.reason;
}

class HandVisionZones {
  final double keyboardYMin;
  final double stylusXMin;
  final double stylusXMax;
  final double stylusYMin;
  final double faceXMin;
  final double faceXMax;
  final double faceYMin;
  final double faceYMax;
  final double deskLineY;

  const HandVisionZones({
    required this.keyboardYMin,
    required this.stylusXMin,
    required this.stylusXMax,
    required this.stylusYMin,
    required this.faceXMin,
    required this.faceXMax,
    required this.faceYMin,
    required this.faceYMax,
    required this.deskLineY,
  });

  @override
  int get hashCode =>
      keyboardYMin.hashCode ^
      stylusXMin.hashCode ^
      stylusXMax.hashCode ^
      stylusYMin.hashCode ^
      faceXMin.hashCode ^
      faceXMax.hashCode ^
      faceYMin.hashCode ^
      faceYMax.hashCode ^
      deskLineY.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HandVisionZones &&
          runtimeType == other.runtimeType &&
          keyboardYMin == other.keyboardYMin &&
          stylusXMin == other.stylusXMin &&
          stylusXMax == other.stylusXMax &&
          stylusYMin == other.stylusYMin &&
          faceXMin == other.faceXMin &&
          faceXMax == other.faceXMax &&
          faceYMin == other.faceYMin &&
          faceYMax == other.faceYMax &&
          deskLineY == other.deskLineY;
}
