// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'air_board.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

HandAirBoardDecision analyzeHandAirBoardContext({
  required HandAirBoardContext context,
}) => BrainCoreApi.instance.api.crateApiHandAirBoardAnalyzeHandAirBoardContext(
  context: context,
);

class HandAirBoardContext {
  final AirBoardActivitySummary airBoard;
  final HandRegionSignal hand;
  final String gazeZone;
  final String screenZone;
  final PlatformInt64 nowMs;

  const HandAirBoardContext({
    required this.airBoard,
    required this.hand,
    required this.gazeZone,
    required this.screenZone,
    required this.nowMs,
  });

  @override
  int get hashCode =>
      airBoard.hashCode ^
      hand.hashCode ^
      gazeZone.hashCode ^
      screenZone.hashCode ^
      nowMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HandAirBoardContext &&
          runtimeType == other.runtimeType &&
          airBoard == other.airBoard &&
          hand == other.hand &&
          gazeZone == other.gazeZone &&
          screenZone == other.screenZone &&
          nowMs == other.nowMs;
}

class HandAirBoardDecision {
  final String behaviourLabel;
  final String attentionLevel;
  final bool handMatchesAirBoard;
  final bool reviewRequired;
  final String studentMessage;
  final String reviewerSummary;

  const HandAirBoardDecision({
    required this.behaviourLabel,
    required this.attentionLevel,
    required this.handMatchesAirBoard,
    required this.reviewRequired,
    required this.studentMessage,
    required this.reviewerSummary,
  });

  @override
  int get hashCode =>
      behaviourLabel.hashCode ^
      attentionLevel.hashCode ^
      handMatchesAirBoard.hashCode ^
      reviewRequired.hashCode ^
      studentMessage.hashCode ^
      reviewerSummary.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HandAirBoardDecision &&
          runtimeType == other.runtimeType &&
          behaviourLabel == other.behaviourLabel &&
          attentionLevel == other.attentionLevel &&
          handMatchesAirBoard == other.handMatchesAirBoard &&
          reviewRequired == other.reviewRequired &&
          studentMessage == other.studentMessage &&
          reviewerSummary == other.reviewerSummary;
}

class HandRegionSignal {
  final bool handVisible;
  final int handCount;
  final double primaryHandX;
  final double primaryHandY;
  final double handConfidence;
  final bool nearKeyboard;
  final bool nearMouseOrStylusArea;
  final bool nearFace;
  final bool belowDeskLine;
  final PlatformInt64 timestampMs;

  const HandRegionSignal({
    required this.handVisible,
    required this.handCount,
    required this.primaryHandX,
    required this.primaryHandY,
    required this.handConfidence,
    required this.nearKeyboard,
    required this.nearMouseOrStylusArea,
    required this.nearFace,
    required this.belowDeskLine,
    required this.timestampMs,
  });

  @override
  int get hashCode =>
      handVisible.hashCode ^
      handCount.hashCode ^
      primaryHandX.hashCode ^
      primaryHandY.hashCode ^
      handConfidence.hashCode ^
      nearKeyboard.hashCode ^
      nearMouseOrStylusArea.hashCode ^
      nearFace.hashCode ^
      belowDeskLine.hashCode ^
      timestampMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HandRegionSignal &&
          runtimeType == other.runtimeType &&
          handVisible == other.handVisible &&
          handCount == other.handCount &&
          primaryHandX == other.primaryHandX &&
          primaryHandY == other.primaryHandY &&
          handConfidence == other.handConfidence &&
          nearKeyboard == other.nearKeyboard &&
          nearMouseOrStylusArea == other.nearMouseOrStylusArea &&
          nearFace == other.nearFace &&
          belowDeskLine == other.belowDeskLine &&
          timestampMs == other.timestampMs;
}
