// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `distance`, `finger_is_extended`, `normalize_coordinate`, `thumb_is_extended`, `unusable`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

HandGestureResult analyzeHandLandmarks({required HandGestureInput input}) =>
    BrainCoreApi.instance.api.crateApiHandGestureAnalyzeHandLandmarks(
      input: input,
    );

class HandGestureInput {
  final List<HandLandmarkPoint> landmarks;
  final int frameWidth;
  final int frameHeight;
  final bool mirrored;
  final PlatformInt64 timestampMs;

  const HandGestureInput({
    required this.landmarks,
    required this.frameWidth,
    required this.frameHeight,
    required this.mirrored,
    required this.timestampMs,
  });

  @override
  int get hashCode =>
      landmarks.hashCode ^
      frameWidth.hashCode ^
      frameHeight.hashCode ^
      mirrored.hashCode ^
      timestampMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HandGestureInput &&
          runtimeType == other.runtimeType &&
          landmarks == other.landmarks &&
          frameWidth == other.frameWidth &&
          frameHeight == other.frameHeight &&
          mirrored == other.mirrored &&
          timestampMs == other.timestampMs;
}

class HandGestureResult {
  final bool usable;
  final String gesture;
  final int fingerCount;
  final bool indexFingerExtended;
  final double indexTipX;
  final double indexTipY;
  final bool writingActive;
  final bool erasingActive;
  final double confidence;
  final String studentMessage;
  final String reason;

  const HandGestureResult({
    required this.usable,
    required this.gesture,
    required this.fingerCount,
    required this.indexFingerExtended,
    required this.indexTipX,
    required this.indexTipY,
    required this.writingActive,
    required this.erasingActive,
    required this.confidence,
    required this.studentMessage,
    required this.reason,
  });

  @override
  int get hashCode =>
      usable.hashCode ^
      gesture.hashCode ^
      fingerCount.hashCode ^
      indexFingerExtended.hashCode ^
      indexTipX.hashCode ^
      indexTipY.hashCode ^
      writingActive.hashCode ^
      erasingActive.hashCode ^
      confidence.hashCode ^
      studentMessage.hashCode ^
      reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HandGestureResult &&
          runtimeType == other.runtimeType &&
          usable == other.usable &&
          gesture == other.gesture &&
          fingerCount == other.fingerCount &&
          indexFingerExtended == other.indexFingerExtended &&
          indexTipX == other.indexTipX &&
          indexTipY == other.indexTipY &&
          writingActive == other.writingActive &&
          erasingActive == other.erasingActive &&
          confidence == other.confidence &&
          studentMessage == other.studentMessage &&
          reason == other.reason;
}

class HandLandmarkPoint {
  final int index;
  final double x;
  final double y;
  final double z;
  final double confidence;

  const HandLandmarkPoint({
    required this.index,
    required this.x,
    required this.y,
    required this.z,
    required this.confidence,
  });

  @override
  int get hashCode =>
      index.hashCode ^
      x.hashCode ^
      y.hashCode ^
      z.hashCode ^
      confidence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HandLandmarkPoint &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          x == other.x &&
          y == other.y &&
          z == other.z &&
          confidence == other.confidence;
}
