// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'hand_gesture.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decode_landmark_output`, `load_model_inner`, `resize_rgb_chw`, `run_landmark_model`, `status_from_manifest`, `unloaded_status`, `unusable_result`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `HandLandmarkManifest`, `HandLandmarkRuntime`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

HandLandmarkModelStatus loadHandLandmarkModel({
  required String manifestJson,
  required List<int> modelBytes,
}) =>
    BrainCoreApi.instance.api.crateApiHandLandmarkRuntimeLoadHandLandmarkModel(
      manifestJson: manifestJson,
      modelBytes: modelBytes,
    );

void clearHandLandmarkModel() => BrainCoreApi.instance.api
    .crateApiHandLandmarkRuntimeClearHandLandmarkModel();

HandLandmarkModelStatus currentHandLandmarkModelStatus() => BrainCoreApi
    .instance
    .api
    .crateApiHandLandmarkRuntimeCurrentHandLandmarkModelStatus();

HandLandmarkInferenceResult analyzeHandLandmarkRgbCrop({
  required List<int> rgbBytes,
  required int cropWidth,
  required int cropHeight,
  required bool mirrored,
  required PlatformInt64 timestampMs,
}) => BrainCoreApi.instance.api
    .crateApiHandLandmarkRuntimeAnalyzeHandLandmarkRgbCrop(
      rgbBytes: rgbBytes,
      cropWidth: cropWidth,
      cropHeight: cropHeight,
      mirrored: mirrored,
      timestampMs: timestampMs,
    );

HandLandmarkInferenceResult reviewHandLandmarkOutput({
  required List<double> output,
  required int landmarkCount,
  required String outputLayout,
  required String coordinateMode,
  int? confidenceIndex,
  required int frameWidth,
  required int frameHeight,
  required bool mirrored,
  required PlatformInt64 timestampMs,
}) => BrainCoreApi.instance.api
    .crateApiHandLandmarkRuntimeReviewHandLandmarkOutput(
      output: output,
      landmarkCount: landmarkCount,
      outputLayout: outputLayout,
      coordinateMode: coordinateMode,
      confidenceIndex: confidenceIndex,
      frameWidth: frameWidth,
      frameHeight: frameHeight,
      mirrored: mirrored,
      timestampMs: timestampMs,
    );

class HandLandmarkInferenceResult {
  final List<HandLandmarkPoint> landmarks;
  final HandGestureResult gesture;
  final bool usable;
  final String reason;

  const HandLandmarkInferenceResult({
    required this.landmarks,
    required this.gesture,
    required this.usable,
    required this.reason,
  });

  @override
  int get hashCode =>
      landmarks.hashCode ^ gesture.hashCode ^ usable.hashCode ^ reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HandLandmarkInferenceResult &&
          runtimeType == other.runtimeType &&
          landmarks == other.landmarks &&
          gesture == other.gesture &&
          usable == other.usable &&
          reason == other.reason;
}

class HandLandmarkModelStatus {
  final bool loaded;
  final String modelName;
  final int inputWidth;
  final int inputHeight;
  final int landmarkCount;
  final String message;

  const HandLandmarkModelStatus({
    required this.loaded,
    required this.modelName,
    required this.inputWidth,
    required this.inputHeight,
    required this.landmarkCount,
    required this.message,
  });

  @override
  int get hashCode =>
      loaded.hashCode ^
      modelName.hashCode ^
      inputWidth.hashCode ^
      inputHeight.hashCode ^
      landmarkCount.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HandLandmarkModelStatus &&
          runtimeType == other.runtimeType &&
          loaded == other.loaded &&
          modelName == other.modelName &&
          inputWidth == other.inputWidth &&
          inputHeight == other.inputHeight &&
          landmarkCount == other.landmarkCount &&
          message == other.message;
}
