// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'hand_air_board.dart';
import 'native_vision.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `empty_result`, `load_hand_vision_model_inner`, `normalize_coordinate`, `resize_rgb_chw`, `run_hand_model`, `status_from_manifest`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `HandVisionManifest`, `HandVisionRuntime`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

HandVisionModelStatus loadHandVisionModel({
  required String manifestJson,
  required List<int> modelBytes,
}) => BrainCoreApi.instance.api.crateApiHandVisionLoadHandVisionModel(
  manifestJson: manifestJson,
  modelBytes: modelBytes,
);

void clearHandVisionModel() =>
    BrainCoreApi.instance.api.crateApiHandVisionClearHandVisionModel();

HandVisionModelStatus currentHandVisionModelStatus() =>
    BrainCoreApi.instance.api.crateApiHandVisionCurrentHandVisionModelStatus();

HandVisionResult analyzeHandRgbFrame({
  required List<int> rgbBytes,
  required int imageWidth,
  required int imageHeight,
  required HandVisionZones zones,
  required PlatformInt64 timestampMs,
}) => BrainCoreApi.instance.api.crateApiHandVisionAnalyzeHandRgbFrame(
  rgbBytes: rgbBytes,
  imageWidth: imageWidth,
  imageHeight: imageHeight,
  zones: zones,
  timestampMs: timestampMs,
);

HandVisionResult reviewHandModelOutput({
  required List<double> output,
  required int numPredictions,
  required int numClasses,
  required int imageWidth,
  required int imageHeight,
  required double confidenceThreshold,
  required double iouThreshold,
  required String layout,
  required List<String> classNames,
  required HandVisionZones zones,
  required PlatformInt64 timestampMs,
}) => BrainCoreApi.instance.api.crateApiHandVisionReviewHandModelOutput(
  output: output,
  numPredictions: numPredictions,
  numClasses: numClasses,
  imageWidth: imageWidth,
  imageHeight: imageHeight,
  confidenceThreshold: confidenceThreshold,
  iouThreshold: iouThreshold,
  layout: layout,
  classNames: classNames,
  zones: zones,
  timestampMs: timestampMs,
);

HandVisionResult reviewHandDetections({
  required List<NativeVisionDetection> detections,
  required int imageWidth,
  required int imageHeight,
  required HandVisionZones zones,
  required PlatformInt64 timestampMs,
}) => BrainCoreApi.instance.api.crateApiHandVisionReviewHandDetections(
  detections: detections,
  imageWidth: imageWidth,
  imageHeight: imageHeight,
  zones: zones,
  timestampMs: timestampMs,
);

class HandVisionModelStatus {
  final bool loaded;
  final String modelName;
  final int inputWidth;
  final int inputHeight;
  final double confidenceThreshold;
  final double iouThreshold;
  final String message;

  const HandVisionModelStatus({
    required this.loaded,
    required this.modelName,
    required this.inputWidth,
    required this.inputHeight,
    required this.confidenceThreshold,
    required this.iouThreshold,
    required this.message,
  });

  @override
  int get hashCode =>
      loaded.hashCode ^
      modelName.hashCode ^
      inputWidth.hashCode ^
      inputHeight.hashCode ^
      confidenceThreshold.hashCode ^
      iouThreshold.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HandVisionModelStatus &&
          runtimeType == other.runtimeType &&
          loaded == other.loaded &&
          modelName == other.modelName &&
          inputWidth == other.inputWidth &&
          inputHeight == other.inputHeight &&
          confidenceThreshold == other.confidenceThreshold &&
          iouThreshold == other.iouThreshold &&
          message == other.message;
}

class HandVisionResult {
  final HandRegionSignal signal;
  final List<NativeVisionDetection> detections;
  final bool usable;
  final String attentionLevel;
  final String reason;

  const HandVisionResult({
    required this.signal,
    required this.detections,
    required this.usable,
    required this.attentionLevel,
    required this.reason,
  });

  @override
  int get hashCode =>
      signal.hashCode ^
      detections.hashCode ^
      usable.hashCode ^
      attentionLevel.hashCode ^
      reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HandVisionResult &&
          runtimeType == other.runtimeType &&
          signal == other.signal &&
          detections == other.detections &&
          usable == other.usable &&
          attentionLevel == other.attentionLevel &&
          reason == other.reason;
}

class HandVisionZones {
  final double keyboardYMin;
  final double stylusXMin;
  final double stylusXMax;
  final double stylusYMin;
  final double faceXMin;
  final double faceXMax;
  final double faceYMin;
  final double faceYMax;
  final double deskLineY;

  const HandVisionZones({
    required this.keyboardYMin,
    required this.stylusXMin,
    required this.stylusXMax,
    required this.stylusYMin,
    required this.faceXMin,
    required this.faceXMax,
    required this.faceYMin,
    required this.faceYMax,
    required this.deskLineY,
  });

  @override
  int get hashCode =>
      keyboardYMin.hashCode ^
      stylusXMin.hashCode ^
      stylusXMax.hashCode ^
      stylusYMin.hashCode ^
      faceXMin.hashCode ^
      faceXMax.hashCode ^
      faceYMin.hashCode ^
      faceYMax.hashCode ^
      deskLineY.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HandVisionZones &&
          runtimeType == other.runtimeType &&
          keyboardYMin == other.keyboardYMin &&
          stylusXMin == other.stylusXMin &&
          stylusXMax == other.stylusXMax &&
          stylusYMin == other.stylusYMin &&
          faceXMin == other.faceXMin &&
          faceXMax == other.faceXMax &&
          faceYMin == other.faceYMin &&
          faceYMax == other.faceYMax &&
          deskLineY == other.deskLineY;
}
