// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `completed_blink`, `movement_progress`, `uncertain`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

/// Evaluates observable motion only. It never makes a misconduct decision.
LivenessChallengeResult analyzeLivenessChallenge({
  required String challenge,
  required List<LivenessObservation> observations,
  required PlatformInt64 startedAtMs,
  required PlatformInt64 deadlineMs,
  required PlatformInt64 nowMs,
}) =>
    BrainCoreApi.instance.api.crateApiLivenessChallengeAnalyzeLivenessChallenge(
      challenge: challenge,
      observations: observations,
      startedAtMs: startedAtMs,
      deadlineMs: deadlineMs,
      nowMs: nowMs,
    );

class LivenessChallengeResult {
  final String state;
  final String challenge;
  final bool completed;
  final bool reliable;
  final double progress;
  final double spoofRiskScore;
  final int usableObservations;
  final String reason;

  const LivenessChallengeResult({
    required this.state,
    required this.challenge,
    required this.completed,
    required this.reliable,
    required this.progress,
    required this.spoofRiskScore,
    required this.usableObservations,
    required this.reason,
  });

  @override
  int get hashCode =>
      state.hashCode ^
      challenge.hashCode ^
      completed.hashCode ^
      reliable.hashCode ^
      progress.hashCode ^
      spoofRiskScore.hashCode ^
      usableObservations.hashCode ^
      reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LivenessChallengeResult &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          challenge == other.challenge &&
          completed == other.completed &&
          reliable == other.reliable &&
          progress == other.progress &&
          spoofRiskScore == other.spoofRiskScore &&
          usableObservations == other.usableObservations &&
          reason == other.reason;
}

class LivenessObservation {
  final PlatformInt64 timestampMs;
  final double faceConfidence;
  final double leftEyeOpen;
  final double rightEyeOpen;
  final double headYaw;
  final double headPitch;
  final double motionScore;
  final bool repeatedFrame;
  final bool flatTexture;

  const LivenessObservation({
    required this.timestampMs,
    required this.faceConfidence,
    required this.leftEyeOpen,
    required this.rightEyeOpen,
    required this.headYaw,
    required this.headPitch,
    required this.motionScore,
    required this.repeatedFrame,
    required this.flatTexture,
  });

  @override
  int get hashCode =>
      timestampMs.hashCode ^
      faceConfidence.hashCode ^
      leftEyeOpen.hashCode ^
      rightEyeOpen.hashCode ^
      headYaw.hashCode ^
      headPitch.hashCode ^
      motionScore.hashCode ^
      repeatedFrame.hashCode ^
      flatTexture.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LivenessObservation &&
          runtimeType == other.runtimeType &&
          timestampMs == other.timestampMs &&
          faceConfidence == other.faceConfidence &&
          leftEyeOpen == other.leftEyeOpen &&
          rightEyeOpen == other.rightEyeOpen &&
          headYaw == other.headYaw &&
          headPitch == other.headPitch &&
          motionScore == other.motionScore &&
          repeatedFrame == other.repeatedFrame &&
          flatTexture == other.flatTexture;
}
