// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `analyse_lockdown`, `command_timeout_hint`, `current_platform_name`, `detect_prohibited_processes`, `is_supported_platform`, `normalise`, `normalized_platform`, `parse_display_count`, `prohibited_process_terms`, `run_command`, `unsupported_result`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

NativeSecureLockdownReviewResult analyzeSecureLockdownReport({
  required String platformName,
  required String processReport,
  int? displayCount,
}) => BrainCoreApi.instance.api.crateApiLockdownAnalyzeSecureLockdownReport(
  platformName: platformName,
  processReport: processReport,
  displayCount: displayCount,
);

Future<String> collectLockdownProcessReport({required String platformName}) =>
    BrainCoreApi.instance.api.crateApiLockdownCollectLockdownProcessReport(
      platformName: platformName,
    );

Future<int?> collectLockdownDisplayCount({required String platformName}) =>
    BrainCoreApi.instance.api.crateApiLockdownCollectLockdownDisplayCount(
      platformName: platformName,
    );

Future<NativeSecureLockdownReviewResult> runSecureLockdownReview({
  required String platformName,
}) => BrainCoreApi.instance.api.crateApiLockdownRunSecureLockdownReview(
  platformName: platformName,
);

class NativeLockdownFinding {
  final String code;
  final String message;
  final String severity;

  const NativeLockdownFinding({
    required this.code,
    required this.message,
    required this.severity,
  });

  @override
  int get hashCode => code.hashCode ^ message.hashCode ^ severity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeLockdownFinding &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message &&
          severity == other.severity;
}

class NativeSecureLockdownReviewResult {
  final bool ready;
  final bool platformSupported;
  final String platformName;
  final int? displayCount;
  final List<String> prohibitedProcesses;
  final List<NativeLockdownFinding> findings;

  const NativeSecureLockdownReviewResult({
    required this.ready,
    required this.platformSupported,
    required this.platformName,
    this.displayCount,
    required this.prohibitedProcesses,
    required this.findings,
  });

  @override
  int get hashCode =>
      ready.hashCode ^
      platformSupported.hashCode ^
      platformName.hashCode ^
      displayCount.hashCode ^
      prohibitedProcesses.hashCode ^
      findings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeSecureLockdownReviewResult &&
          runtimeType == other.runtimeType &&
          ready == other.ready &&
          platformSupported == other.platformSupported &&
          platformName == other.platformName &&
          displayCount == other.displayCount &&
          prohibitedProcesses == other.prohibitedProcesses &&
          findings == other.findings;
}
