// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `normalize_capacity`, `require_session_id`, `to_ingest_result`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

/// Transitional JSON ingress for the frozen ModelEventV1 contract.
///
/// JSON is intentionally used at the integration boundary while the event bus
/// is being migrated. The internal memory is Rust-owned and typed. E1 person
/// observations are enriched with conservative short-term persistent track IDs
/// here before storage, keeping stateful tracking out of Flutter.
ModelEventIngestResultV1 ingestModelEventV1Json({
  required String eventJson,
  BigInt? requestedCapacity,
}) => RustLib.instance.api.crateApiModelEventMemoryIngestModelEventV1Json(
  eventJson: eventJson,
  requestedCapacity: requestedCapacity,
);

ModelEventMemoryStatusV1 modelEventMemoryStatusV1({
  required String sessionId,
}) => RustLib.instance.api.crateApiModelEventMemoryModelEventMemoryStatusV1(
  sessionId: sessionId,
);

String readModelEventsBetweenV1Json({
  required String sessionId,
  required BigInt startCaptureTimestampNs,
  required BigInt endCaptureTimestampNs,
}) => RustLib.instance.api.crateApiModelEventMemoryReadModelEventsBetweenV1Json(
  sessionId: sessionId,
  startCaptureTimestampNs: startCaptureTimestampNs,
  endCaptureTimestampNs: endCaptureTimestampNs,
);

String readModelEventsActiveAtV1Json({
  required String sessionId,
  required BigInt timestampNs,
}) =>
    RustLib.instance.api.crateApiModelEventMemoryReadModelEventsActiveAtV1Json(
      sessionId: sessionId,
      timestampNs: timestampNs,
    );

bool clearModelEventMemoryV1({required String sessionId}) => RustLib
    .instance
    .api
    .crateApiModelEventMemoryClearModelEventMemoryV1(sessionId: sessionId);

class ModelEventIngestResultV1 {
  final String sessionId;
  final String eventId;
  final bool retained;
  final String? evictedEventId;
  final BigInt len;
  final BigInt capacity;

  const ModelEventIngestResultV1({
    required this.sessionId,
    required this.eventId,
    required this.retained,
    this.evictedEventId,
    required this.len,
    required this.capacity,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      eventId.hashCode ^
      retained.hashCode ^
      evictedEventId.hashCode ^
      len.hashCode ^
      capacity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelEventIngestResultV1 &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          eventId == other.eventId &&
          retained == other.retained &&
          evictedEventId == other.evictedEventId &&
          len == other.len &&
          capacity == other.capacity;
}

class ModelEventMemoryStatusV1 {
  final String sessionId;
  final bool exists;
  final BigInt len;
  final BigInt capacity;

  const ModelEventMemoryStatusV1({
    required this.sessionId,
    required this.exists,
    required this.len,
    required this.capacity,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^ exists.hashCode ^ len.hashCode ^ capacity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelEventMemoryStatusV1 &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          exists == other.exists &&
          len == other.len &&
          capacity == other.capacity;
}
