// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `require_text`, `validate_finite`, `validate_unit_interval`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ModelEventV1>>
abstract class ModelEventV1 implements RustOpaqueInterface {
  BigInt get captureTimestampNs;

  String get classId;

  double? get confidence;

  String get eventId;

  ModelGeometryV1? get geometry;

  BigInt get inferenceTimestampNs;

  BTreeMapStringValue get metadata;

  String get modelId;

  String get modelVersion;

  double? get quality;

  String get schemaVersion;

  String get sessionId;

  BigInt? get sourceFrameId;

  String? get trackId;

  ValidityIntervalV1 get validityInterval;

  set captureTimestampNs(BigInt captureTimestampNs);

  set classId(String classId);

  set confidence(double? confidence);

  set eventId(String eventId);

  set geometry(ModelGeometryV1? geometry);

  set inferenceTimestampNs(BigInt inferenceTimestampNs);

  set metadata(BTreeMapStringValue metadata);

  set modelId(String modelId);

  set modelVersion(String modelVersion);

  set quality(double? quality);

  set schemaVersion(String schemaVersion);

  set sessionId(String sessionId);

  set sourceFrameId(BigInt? sourceFrameId);

  set trackId(String? trackId);

  set validityInterval(ValidityIntervalV1 validityInterval);

  static Future<ModelEventV1> fromJson({required String value}) => BrainCoreApi
      .instance
      .api
      .crateApiModelEventModelEventV1FromJson(value: value);

  Future<String> toJson();

  Future<void> validate();
}

class BoundingBoxV1 {
  final double x;
  final double y;
  final double width;
  final double height;

  const BoundingBoxV1({
    required this.x,
    required this.y,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode =>
      x.hashCode ^ y.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BoundingBoxV1 &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          width == other.width &&
          height == other.height;
}

class KeypointV1 {
  final double x;
  final double y;
  final double? confidence;
  final String? label;

  const KeypointV1({
    required this.x,
    required this.y,
    this.confidence,
    this.label,
  });

  @override
  int get hashCode =>
      x.hashCode ^ y.hashCode ^ confidence.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeypointV1 &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y &&
          confidence == other.confidence &&
          label == other.label;
}

class ModelGeometryV1 {
  final String? coordinateSpace;
  final BoundingBoxV1? boundingBox;
  final List<KeypointV1> keypoints;
  final Float32List? vector;
  final String? regionId;

  const ModelGeometryV1({
    this.coordinateSpace,
    this.boundingBox,
    required this.keypoints,
    this.vector,
    this.regionId,
  });

  static Future<ModelGeometryV1> default_() =>
      BrainCoreApi.instance.api.crateApiModelEventModelGeometryV1Default();

  Future<void> validate() => BrainCoreApi.instance.api
      .crateApiModelEventModelGeometryV1Validate(that: this);

  @override
  int get hashCode =>
      coordinateSpace.hashCode ^
      boundingBox.hashCode ^
      keypoints.hashCode ^
      vector.hashCode ^
      regionId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModelGeometryV1 &&
          runtimeType == other.runtimeType &&
          coordinateSpace == other.coordinateSpace &&
          boundingBox == other.boundingBox &&
          keypoints == other.keypoints &&
          vector == other.vector &&
          regionId == other.regionId;
}

class ValidityIntervalV1 {
  final BigInt startTimestampNs;
  final BigInt? endTimestampNs;

  const ValidityIntervalV1({
    required this.startTimestampNs,
    this.endTimestampNs,
  });

  Future<void> validate() => BrainCoreApi.instance.api
      .crateApiModelEventValidityIntervalV1Validate(that: this);

  @override
  int get hashCode => startTimestampNs.hashCode ^ endTimestampNs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ValidityIntervalV1 &&
          runtimeType == other.runtimeType &&
          startTimestampNs == other.startTimestampNs &&
          endTimestampNs == other.endTimestampNs;
}
