// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `approximate_sharpness`, `decode_predictions`, `frame_quality`, `gather_channels_first`, `gather_row`, `head_pose`, `iou`, `is_book`, `is_paper`, `is_person`, `is_phone`, `non_max_suppression`, `normalize_box`, `object_review`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

NativeVisionFrameQuality analyzeRgbFrameQuality({
  required int width,
  required int height,
  required List<int> rgbBytes,
}) => BrainCoreApi.instance.api.crateApiNativeVisionAnalyzeRgbFrameQuality(
  width: width,
  height: height,
  rgbBytes: rgbBytes,
);

NativeObjectReviewResult decodeYoloOutput({
  required List<double> output,
  required int numPredictions,
  required int numClasses,
  required int imageWidth,
  required int imageHeight,
  required double confidenceThreshold,
  required double iouThreshold,
  required String layout,
  required List<String> classNames,
}) => BrainCoreApi.instance.api.crateApiNativeVisionDecodeYoloOutput(
  output: output,
  numPredictions: numPredictions,
  numClasses: numClasses,
  imageWidth: imageWidth,
  imageHeight: imageHeight,
  confidenceThreshold: confidenceThreshold,
  iouThreshold: iouThreshold,
  layout: layout,
  classNames: classNames,
);

NativeObjectReviewResult reviewObjectDetections({
  required List<NativeVisionDetection> detections,
  required double iouThreshold,
}) => BrainCoreApi.instance.api.crateApiNativeVisionReviewObjectDetections(
  detections: detections,
  iouThreshold: iouThreshold,
);

NativeHeadPoseReviewResult analyzeHeadPoseGeometry({
  required double leftEyeX,
  required double leftEyeY,
  required double rightEyeX,
  required double rightEyeY,
  required double noseX,
  required double noseY,
  required double mouthX,
  required double mouthY,
  required double faceWidth,
  required double faceHeight,
}) => BrainCoreApi.instance.api.crateApiNativeVisionAnalyzeHeadPoseGeometry(
  leftEyeX: leftEyeX,
  leftEyeY: leftEyeY,
  rightEyeX: rightEyeX,
  rightEyeY: rightEyeY,
  noseX: noseX,
  noseY: noseY,
  mouthX: mouthX,
  mouthY: mouthY,
  faceWidth: faceWidth,
  faceHeight: faceHeight,
);

class NativeHeadPoseReviewResult {
  final bool usable;
  final bool lookingAway;
  final double yawScore;
  final double pitchScore;
  final double rollScore;
  final String attentionLevel;
  final String reason;

  const NativeHeadPoseReviewResult({
    required this.usable,
    required this.lookingAway,
    required this.yawScore,
    required this.pitchScore,
    required this.rollScore,
    required this.attentionLevel,
    required this.reason,
  });

  @override
  int get hashCode =>
      usable.hashCode ^
      lookingAway.hashCode ^
      yawScore.hashCode ^
      pitchScore.hashCode ^
      rollScore.hashCode ^
      attentionLevel.hashCode ^
      reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeHeadPoseReviewResult &&
          runtimeType == other.runtimeType &&
          usable == other.usable &&
          lookingAway == other.lookingAway &&
          yawScore == other.yawScore &&
          pitchScore == other.pitchScore &&
          rollScore == other.rollScore &&
          attentionLevel == other.attentionLevel &&
          reason == other.reason;
}

class NativeObjectReviewResult {
  final List<NativeVisionDetection> detections;
  final int peopleCount;
  final int phoneCount;
  final int bookCount;
  final int paperCount;
  final bool needsReview;
  final String attentionLevel;
  final String reason;

  const NativeObjectReviewResult({
    required this.detections,
    required this.peopleCount,
    required this.phoneCount,
    required this.bookCount,
    required this.paperCount,
    required this.needsReview,
    required this.attentionLevel,
    required this.reason,
  });

  @override
  int get hashCode =>
      detections.hashCode ^
      peopleCount.hashCode ^
      phoneCount.hashCode ^
      bookCount.hashCode ^
      paperCount.hashCode ^
      needsReview.hashCode ^
      attentionLevel.hashCode ^
      reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeObjectReviewResult &&
          runtimeType == other.runtimeType &&
          detections == other.detections &&
          peopleCount == other.peopleCount &&
          phoneCount == other.phoneCount &&
          bookCount == other.bookCount &&
          paperCount == other.paperCount &&
          needsReview == other.needsReview &&
          attentionLevel == other.attentionLevel &&
          reason == other.reason;
}

class NativeVisionDetection {
  final int classId;
  final String label;
  final double confidence;
  final double xCenter;
  final double yCenter;
  final double width;
  final double height;
  final double xMin;
  final double yMin;
  final double xMax;
  final double yMax;

  const NativeVisionDetection({
    required this.classId,
    required this.label,
    required this.confidence,
    required this.xCenter,
    required this.yCenter,
    required this.width,
    required this.height,
    required this.xMin,
    required this.yMin,
    required this.xMax,
    required this.yMax,
  });

  @override
  int get hashCode =>
      classId.hashCode ^
      label.hashCode ^
      confidence.hashCode ^
      xCenter.hashCode ^
      yCenter.hashCode ^
      width.hashCode ^
      height.hashCode ^
      xMin.hashCode ^
      yMin.hashCode ^
      xMax.hashCode ^
      yMax.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeVisionDetection &&
          runtimeType == other.runtimeType &&
          classId == other.classId &&
          label == other.label &&
          confidence == other.confidence &&
          xCenter == other.xCenter &&
          yCenter == other.yCenter &&
          width == other.width &&
          height == other.height &&
          xMin == other.xMin &&
          yMin == other.yMin &&
          xMax == other.xMax &&
          yMax == other.yMax;
}

class NativeVisionFrameQuality {
  final bool isUsable;
  final double brightness;
  final double contrast;
  final double sharpness;
  final String reason;

  const NativeVisionFrameQuality({
    required this.isUsable,
    required this.brightness,
    required this.contrast,
    required this.sharpness,
    required this.reason,
  });

  @override
  int get hashCode =>
      isUsable.hashCode ^
      brightness.hashCode ^
      contrast.hashCode ^
      sharpness.hashCode ^
      reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeVisionFrameQuality &&
          runtimeType == other.runtimeType &&
          isUsable == other.isUsable &&
          brightness == other.brightness &&
          contrast == other.contrast &&
          sharpness == other.sharpness &&
          reason == other.reason;
}
