// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'model_event.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `attach_tracking_metadata`, `best_match`, `center_distance`, `center`, `create_track`, `enrich_event`, `expire_stale_tracks`, `iou`, `is_person_class`, `motion_state`, `new`, `predicted_box`, `track_seen_in_same_frame`, `update_track`, `valid_normalized_box`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PersonTrackEnrichmentV1`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`

class PersonTrackStateV1 {
  final String trackId;
  final BigInt firstSeenNs;
  final BigInt lastSeenNs;
  final BigInt? lastSourceFrameId;
  final BoundingBoxV1 lastBox;
  final double velocityXPerSecond;
  final double velocityYPerSecond;
  final BigInt hitCount;
  final BigInt gapRecoveryCount;

  const PersonTrackStateV1({
    required this.trackId,
    required this.firstSeenNs,
    required this.lastSeenNs,
    this.lastSourceFrameId,
    required this.lastBox,
    required this.velocityXPerSecond,
    required this.velocityYPerSecond,
    required this.hitCount,
    required this.gapRecoveryCount,
  });

  @override
  int get hashCode =>
      trackId.hashCode ^
      firstSeenNs.hashCode ^
      lastSeenNs.hashCode ^
      lastSourceFrameId.hashCode ^
      lastBox.hashCode ^
      velocityXPerSecond.hashCode ^
      velocityYPerSecond.hashCode ^
      hitCount.hashCode ^
      gapRecoveryCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PersonTrackStateV1 &&
          runtimeType == other.runtimeType &&
          trackId == other.trackId &&
          firstSeenNs == other.firstSeenNs &&
          lastSeenNs == other.lastSeenNs &&
          lastSourceFrameId == other.lastSourceFrameId &&
          lastBox == other.lastBox &&
          velocityXPerSecond == other.velocityXPerSecond &&
          velocityYPerSecond == other.velocityYPerSecond &&
          hitCount == other.hitCount &&
          gapRecoveryCount == other.gapRecoveryCount;
}

class PersonTrackerV1 {
  final BigInt nextTrackNumber;
  final BigInt? latestCaptureTimestampNs;
  final Map<String, PersonTrackStateV1> tracks;

  const PersonTrackerV1({
    required this.nextTrackNumber,
    this.latestCaptureTimestampNs,
    required this.tracks,
  });

  static Future<PersonTrackerV1> default_() =>
      BrainCoreApi.instance.api.crateApiPersonTrackerPersonTrackerV1Default();

  @override
  int get hashCode =>
      nextTrackNumber.hashCode ^
      latestCaptureTimestampNs.hashCode ^
      tracks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PersonTrackerV1 &&
          runtimeType == other.runtimeType &&
          nextTrackNumber == other.nextTrackNumber &&
          latestCaptureTimestampNs == other.latestCaptureTimestampNs &&
          tracks == other.tracks;
}
