// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clamp_dbfs`, `detect_rectangular_device_labels`, `extract_luma_buffer`, `is_background_label`, `load_vision_model_inner`, `normalize_label`, `normalize_signal_from_dbfs`, `pcm16le_rms_dbfs`, `resize_luma_nn`, `run_vision_model`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `VisionModelManifest`, `VisionRuntime`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

AcousticSampleDecision processAcousticSample({
  required double dbfs,
  required double lossThresholdDbfs,
  required int lossStreak,
  required int lossSamplesToTrigger,
}) => BrainCoreApi.instance.api.crateApiProctoringProcessAcousticSample(
  dbfs: dbfs,
  lossThresholdDbfs: lossThresholdDbfs,
  lossStreak: lossStreak,
  lossSamplesToTrigger: lossSamplesToTrigger,
);

AcousticAnalysisDecision analyzeAcousticChunk({
  required List<int> pcm16Bytes,
  required double lossThresholdDbfs,
  required int lossStreak,
  required int lossSamplesToTrigger,
  required double speechThresholdDbfs,
  required int speechStreak,
  required int speechSamplesToTrigger,
  required PlatformInt64 lastSpeechStrikeAtMs,
  required PlatformInt64 speechCooldownMs,
  required PlatformInt64 nowMs,
}) => BrainCoreApi.instance.api.crateApiProctoringAnalyzeAcousticChunk(
  pcm16Bytes: pcm16Bytes,
  lossThresholdDbfs: lossThresholdDbfs,
  lossStreak: lossStreak,
  lossSamplesToTrigger: lossSamplesToTrigger,
  speechThresholdDbfs: speechThresholdDbfs,
  speechStreak: speechStreak,
  speechSamplesToTrigger: speechSamplesToTrigger,
  lastSpeechStrikeAtMs: lastSpeechStrikeAtMs,
  speechCooldownMs: speechCooldownMs,
  nowMs: nowMs,
);

MotionAnalysisDecision analyzeMotionSample({
  required double x,
  required double y,
  required double z,
  required double xThreshold,
  required double yThreshold,
  required double zThreshold,
  required PlatformInt64 nowMs,
  required PlatformInt64 lastViolationAtMs,
  required PlatformInt64 cooldownMs,
  required PlatformInt64 windowStartMs,
  required PlatformInt64 windowMs,
  required int burstCount,
  required int burstThreshold,
}) => BrainCoreApi.instance.api.crateApiProctoringAnalyzeMotionSample(
  x: x,
  y: y,
  z: z,
  xThreshold: xThreshold,
  yThreshold: yThreshold,
  zThreshold: zThreshold,
  nowMs: nowMs,
  lastViolationAtMs: lastViolationAtMs,
  cooldownMs: cooldownMs,
  windowStartMs: windowStartMs,
  windowMs: windowMs,
  burstCount: burstCount,
  burstThreshold: burstThreshold,
);

RotationAnalysisDecision updateRotationProgress({
  required double x,
  required double y,
  required double z,
  required double accumulated,
  required double currentProgress,
  required double deltaScale,
  required double minDelta,
  required double targetAccumulated,
}) => BrainCoreApi.instance.api.crateApiProctoringUpdateRotationProgress(
  x: x,
  y: y,
  z: z,
  accumulated: accumulated,
  currentProgress: currentProgress,
  deltaScale: deltaScale,
  minDelta: minDelta,
  targetAccumulated: targetAccumulated,
);

FaceAnalysisDecision analyzeFaceState({
  required int faceCount,
  required bool includeGaze,
  required double yaw,
  required double pitch,
  required PlatformInt64 nowMs,
  required PlatformInt64 lastMultiFaceStrikeAtMs,
  required PlatformInt64 multiFaceCooldownMs,
  PlatformInt64? gazeAwayStartedAtMs,
  required PlatformInt64 gazeAwayDurationMs,
  required PlatformInt64 lastGazeWarningAtMs,
  required PlatformInt64 gazeWarningCooldownMs,
  required double yawThreshold,
  required double pitchThreshold,
}) => BrainCoreApi.instance.api.crateApiProctoringAnalyzeFaceState(
  faceCount: faceCount,
  includeGaze: includeGaze,
  yaw: yaw,
  pitch: pitch,
  nowMs: nowMs,
  lastMultiFaceStrikeAtMs: lastMultiFaceStrikeAtMs,
  multiFaceCooldownMs: multiFaceCooldownMs,
  gazeAwayStartedAtMs: gazeAwayStartedAtMs,
  gazeAwayDurationMs: gazeAwayDurationMs,
  lastGazeWarningAtMs: lastGazeWarningAtMs,
  gazeWarningCooldownMs: gazeWarningCooldownMs,
  yawThreshold: yawThreshold,
  pitchThreshold: pitchThreshold,
);

EnvironmentFrameDecision analyzeEnvironmentFrame({
  required List<String> objectLabels,
  required double lightingScore,
  required bool rotationCovered,
  required List<String> forbiddenKeywords,
}) => BrainCoreApi.instance.api.crateApiProctoringAnalyzeEnvironmentFrame(
  objectLabels: objectLabels,
  lightingScore: lightingScore,
  rotationCovered: rotationCovered,
  forbiddenKeywords: forbiddenKeywords,
);

double estimateLightingFromLuma({
  required List<int> lumaBytes,
  required int sampleStride,
}) => BrainCoreApi.instance.api.crateApiProctoringEstimateLightingFromLuma(
  lumaBytes: lumaBytes,
  sampleStride: sampleStride,
);

GazeHeadPoseDecision? analyzeGazeHeadPoseFrame({
  required List<int> plane0Bytes,
  required int width,
  required int height,
  required int bytesPerRow,
  required double previousYaw,
  required double previousPitch,
  required double previousRoll,
}) => BrainCoreApi.instance.api.crateApiProctoringAnalyzeGazeHeadPoseFrame(
  plane0Bytes: plane0Bytes,
  width: width,
  height: height,
  bytesPerRow: bytesPerRow,
  previousYaw: previousYaw,
  previousPitch: previousPitch,
  previousRoll: previousRoll,
);

VisionModelStatus loadVisionModel({
  required String manifestJson,
  required List<int> modelBytes,
}) => BrainCoreApi.instance.api.crateApiProctoringLoadVisionModel(
  manifestJson: manifestJson,
  modelBytes: modelBytes,
);

void clearVisionModel() =>
    BrainCoreApi.instance.api.crateApiProctoringClearVisionModel();

VisionModelStatus currentVisionModelStatus() =>
    BrainCoreApi.instance.api.crateApiProctoringCurrentVisionModelStatus();

ScanFrameDecision analyzeScanFrame({
  required List<int> plane0Bytes,
  required int width,
  required int height,
  required int bytesPerRow,
  required String pixelFormat,
}) => BrainCoreApi.instance.api.crateApiProctoringAnalyzeScanFrame(
  plane0Bytes: plane0Bytes,
  width: width,
  height: height,
  bytesPerRow: bytesPerRow,
  pixelFormat: pixelFormat,
);

class AcousticAnalysisDecision {
  final double dbfs;
  final int updatedLossStreak;
  final bool shouldTriggerScan;
  final double normalizedTetherSignal;
  final int updatedSpeechStreak;
  final bool shouldTriggerSpeech;
  final PlatformInt64 updatedLastSpeechStrikeAtMs;

  const AcousticAnalysisDecision({
    required this.dbfs,
    required this.updatedLossStreak,
    required this.shouldTriggerScan,
    required this.normalizedTetherSignal,
    required this.updatedSpeechStreak,
    required this.shouldTriggerSpeech,
    required this.updatedLastSpeechStrikeAtMs,
  });

  @override
  int get hashCode =>
      dbfs.hashCode ^
      updatedLossStreak.hashCode ^
      shouldTriggerScan.hashCode ^
      normalizedTetherSignal.hashCode ^
      updatedSpeechStreak.hashCode ^
      shouldTriggerSpeech.hashCode ^
      updatedLastSpeechStrikeAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AcousticAnalysisDecision &&
          runtimeType == other.runtimeType &&
          dbfs == other.dbfs &&
          updatedLossStreak == other.updatedLossStreak &&
          shouldTriggerScan == other.shouldTriggerScan &&
          normalizedTetherSignal == other.normalizedTetherSignal &&
          updatedSpeechStreak == other.updatedSpeechStreak &&
          shouldTriggerSpeech == other.shouldTriggerSpeech &&
          updatedLastSpeechStrikeAtMs == other.updatedLastSpeechStrikeAtMs;
}

class AcousticSampleDecision {
  final int updatedLossStreak;
  final bool shouldTriggerScan;
  final double normalizedTetherSignal;

  const AcousticSampleDecision({
    required this.updatedLossStreak,
    required this.shouldTriggerScan,
    required this.normalizedTetherSignal,
  });

  @override
  int get hashCode =>
      updatedLossStreak.hashCode ^
      shouldTriggerScan.hashCode ^
      normalizedTetherSignal.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AcousticSampleDecision &&
          runtimeType == other.runtimeType &&
          updatedLossStreak == other.updatedLossStreak &&
          shouldTriggerScan == other.shouldTriggerScan &&
          normalizedTetherSignal == other.normalizedTetherSignal;
}

class EnvironmentFrameDecision {
  final double normalizedLightingScore;
  final bool rotationConfirmed;
  final List<String> forbiddenObjects;

  const EnvironmentFrameDecision({
    required this.normalizedLightingScore,
    required this.rotationConfirmed,
    required this.forbiddenObjects,
  });

  @override
  int get hashCode =>
      normalizedLightingScore.hashCode ^
      rotationConfirmed.hashCode ^
      forbiddenObjects.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnvironmentFrameDecision &&
          runtimeType == other.runtimeType &&
          normalizedLightingScore == other.normalizedLightingScore &&
          rotationConfirmed == other.rotationConfirmed &&
          forbiddenObjects == other.forbiddenObjects;
}

class FaceAnalysisDecision {
  final bool shouldFlagMultiFace;
  final bool shouldWarnGaze;
  final PlatformInt64 updatedLastMultiFaceStrikeAtMs;
  final PlatformInt64 updatedLastGazeWarningAtMs;
  final PlatformInt64? updatedGazeAwayStartedAtMs;

  const FaceAnalysisDecision({
    required this.shouldFlagMultiFace,
    required this.shouldWarnGaze,
    required this.updatedLastMultiFaceStrikeAtMs,
    required this.updatedLastGazeWarningAtMs,
    this.updatedGazeAwayStartedAtMs,
  });

  @override
  int get hashCode =>
      shouldFlagMultiFace.hashCode ^
      shouldWarnGaze.hashCode ^
      updatedLastMultiFaceStrikeAtMs.hashCode ^
      updatedLastGazeWarningAtMs.hashCode ^
      updatedGazeAwayStartedAtMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FaceAnalysisDecision &&
          runtimeType == other.runtimeType &&
          shouldFlagMultiFace == other.shouldFlagMultiFace &&
          shouldWarnGaze == other.shouldWarnGaze &&
          updatedLastMultiFaceStrikeAtMs ==
              other.updatedLastMultiFaceStrikeAtMs &&
          updatedLastGazeWarningAtMs == other.updatedLastGazeWarningAtMs &&
          updatedGazeAwayStartedAtMs == other.updatedGazeAwayStartedAtMs;
}

class GazeHeadPoseDecision {
  final double gazeX;
  final double gazeY;
  final double gazeZ;
  final double yawProxy;
  final double pitchProxy;
  final double rollProxy;
  final double confidence;
  final bool stableHeadPose;
  final bool lookingAway;
  final String label;

  const GazeHeadPoseDecision({
    required this.gazeX,
    required this.gazeY,
    required this.gazeZ,
    required this.yawProxy,
    required this.pitchProxy,
    required this.rollProxy,
    required this.confidence,
    required this.stableHeadPose,
    required this.lookingAway,
    required this.label,
  });

  @override
  int get hashCode =>
      gazeX.hashCode ^
      gazeY.hashCode ^
      gazeZ.hashCode ^
      yawProxy.hashCode ^
      pitchProxy.hashCode ^
      rollProxy.hashCode ^
      confidence.hashCode ^
      stableHeadPose.hashCode ^
      lookingAway.hashCode ^
      label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GazeHeadPoseDecision &&
          runtimeType == other.runtimeType &&
          gazeX == other.gazeX &&
          gazeY == other.gazeY &&
          gazeZ == other.gazeZ &&
          yawProxy == other.yawProxy &&
          pitchProxy == other.pitchProxy &&
          rollProxy == other.rollProxy &&
          confidence == other.confidence &&
          stableHeadPose == other.stableHeadPose &&
          lookingAway == other.lookingAway &&
          label == other.label;
}

class MotionAnalysisDecision {
  final bool moved;
  final bool shouldLogViolation;
  final bool shouldTriggerScan;
  final PlatformInt64 updatedLastViolationAtMs;
  final PlatformInt64 updatedWindowStartMs;
  final int updatedBurstCount;

  const MotionAnalysisDecision({
    required this.moved,
    required this.shouldLogViolation,
    required this.shouldTriggerScan,
    required this.updatedLastViolationAtMs,
    required this.updatedWindowStartMs,
    required this.updatedBurstCount,
  });

  @override
  int get hashCode =>
      moved.hashCode ^
      shouldLogViolation.hashCode ^
      shouldTriggerScan.hashCode ^
      updatedLastViolationAtMs.hashCode ^
      updatedWindowStartMs.hashCode ^
      updatedBurstCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MotionAnalysisDecision &&
          runtimeType == other.runtimeType &&
          moved == other.moved &&
          shouldLogViolation == other.shouldLogViolation &&
          shouldTriggerScan == other.shouldTriggerScan &&
          updatedLastViolationAtMs == other.updatedLastViolationAtMs &&
          updatedWindowStartMs == other.updatedWindowStartMs &&
          updatedBurstCount == other.updatedBurstCount;
}

class RotationAnalysisDecision {
  final double updatedAccumulated;
  final double updatedProgress;
  final bool rotationConfirmed;

  const RotationAnalysisDecision({
    required this.updatedAccumulated,
    required this.updatedProgress,
    required this.rotationConfirmed,
  });

  @override
  int get hashCode =>
      updatedAccumulated.hashCode ^
      updatedProgress.hashCode ^
      rotationConfirmed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RotationAnalysisDecision &&
          runtimeType == other.runtimeType &&
          updatedAccumulated == other.updatedAccumulated &&
          updatedProgress == other.updatedProgress &&
          rotationConfirmed == other.rotationConfirmed;
}

class ScanFrameDecision {
  final double lightingScore;
  final List<String> objectLabels;
  final int faceCount;
  final double estimatedYaw;
  final double estimatedPitch;

  const ScanFrameDecision({
    required this.lightingScore,
    required this.objectLabels,
    required this.faceCount,
    required this.estimatedYaw,
    required this.estimatedPitch,
  });

  @override
  int get hashCode =>
      lightingScore.hashCode ^
      objectLabels.hashCode ^
      faceCount.hashCode ^
      estimatedYaw.hashCode ^
      estimatedPitch.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanFrameDecision &&
          runtimeType == other.runtimeType &&
          lightingScore == other.lightingScore &&
          objectLabels == other.objectLabels &&
          faceCount == other.faceCount &&
          estimatedYaw == other.estimatedYaw &&
          estimatedPitch == other.estimatedPitch;
}

class VisionModelStatus {
  final bool loaded;
  final String modelName;
  final int inputWidth;
  final int inputHeight;
  final double confidenceThreshold;
  final int labelCount;
  final String message;

  const VisionModelStatus({
    required this.loaded,
    required this.modelName,
    required this.inputWidth,
    required this.inputHeight,
    required this.confidenceThreshold,
    required this.labelCount,
    required this.message,
  });

  @override
  int get hashCode =>
      loaded.hashCode ^
      modelName.hashCode ^
      inputWidth.hashCode ^
      inputHeight.hashCode ^
      confidenceThreshold.hashCode ^
      labelCount.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VisionModelStatus &&
          runtimeType == other.runtimeType &&
          loaded == other.loaded &&
          modelName == other.modelName &&
          inputWidth == other.inputWidth &&
          inputHeight == other.inputHeight &&
          confidenceThreshold == other.confidenceThreshold &&
          labelCount == other.labelCount &&
          message == other.message;
}
