// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'model_event.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `event_order`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `eq`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SpatiotemporalRingBufferV1>>
abstract class SpatiotemporalRingBufferV1 implements RustOpaqueInterface {
  Future<BigInt> capacity();

  Future<void> clear();

  Future<bool> containsEventId({required String eventId});

  Future<List<ModelEventV1>> eventsActiveAt({required BigInt timestampNs});

  Future<List<ModelEventV1>> eventsBetween({
    required BigInt startCaptureTimestampNs,
    required BigInt endCaptureTimestampNs,
  });

  Future<bool> isEmpty();

  Future<ModelEventV1?> latestForClass({
    required String classId,
    Str? trackId,
    required BigInt atOrBeforeCaptureTimestampNs,
  });

  Future<BigInt> len();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<SpatiotemporalRingBufferV1> newInstance({
    required String sessionId,
    required BigInt capacity,
  }) => BrainCoreApi.instance.api
      .crateApiSpatiotemporalBufferSpatiotemporalRingBufferV1New(
        sessionId: sessionId,
        capacity: capacity,
      );

  Future<RingBufferInsertResultV1> push({required ModelEventV1 event});

  Future<void> sessionId();

  Future<List<ModelEventV1>> snapshot();
}

class RingBufferInsertResultV1 {
  final bool retained;
  final String? evictedEventId;
  final BigInt len;
  final BigInt capacity;

  const RingBufferInsertResultV1({
    required this.retained,
    this.evictedEventId,
    required this.len,
    required this.capacity,
  });

  @override
  int get hashCode =>
      retained.hashCode ^
      evictedEventId.hashCode ^
      len.hashCode ^
      capacity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RingBufferInsertResultV1 &&
          runtimeType == other.runtimeType &&
          retained == other.retained &&
          evictedEventId == other.evictedEventId &&
          len == other.len &&
          capacity == other.capacity;
}
