// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `analyse_output`, `command_timeout_hint`, `contains_any`, `current_platform_name`, `is_supported_platform`, `normalise`, `normalized_platform`, `run_command`, `unsupported_result`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

NativeSystemSecurityReviewResult analyzeSystemSecurityReport({
  required String report,
  required String platformName,
}) =>
    BrainCoreApi.instance.api.crateApiSystemSecurityAnalyzeSystemSecurityReport(
      report: report,
      platformName: platformName,
    );

Future<String> collectSystemSecurityReport({required String platformName}) =>
    BrainCoreApi.instance.api.crateApiSystemSecurityCollectSystemSecurityReport(
      platformName: platformName,
    );

Future<NativeSystemSecurityReviewResult> runSystemSecurityReview({
  required String platformName,
}) => BrainCoreApi.instance.api.crateApiSystemSecurityRunSystemSecurityReview(
  platformName: platformName,
);

class NativeSystemSecurityReviewResult {
  final bool ready;
  final bool platformSupported;
  final bool bluetoothDetected;
  final bool externalAudioDetected;
  final bool usbRiskDetected;
  final bool virtualizationDetected;
  final bool virtualizationWarningDetected;
  final bool containerDetected;
  final bool virtualCameraDetected;
  final bool unknownDeviceState;
  final List<String> findings;
  final List<String> hardFindings;
  final List<String> warningFindings;
  final String message;

  const NativeSystemSecurityReviewResult({
    required this.ready,
    required this.platformSupported,
    required this.bluetoothDetected,
    required this.externalAudioDetected,
    required this.usbRiskDetected,
    required this.virtualizationDetected,
    required this.virtualizationWarningDetected,
    required this.containerDetected,
    required this.virtualCameraDetected,
    required this.unknownDeviceState,
    required this.findings,
    required this.hardFindings,
    required this.warningFindings,
    required this.message,
  });

  @override
  int get hashCode =>
      ready.hashCode ^
      platformSupported.hashCode ^
      bluetoothDetected.hashCode ^
      externalAudioDetected.hashCode ^
      usbRiskDetected.hashCode ^
      virtualizationDetected.hashCode ^
      virtualizationWarningDetected.hashCode ^
      containerDetected.hashCode ^
      virtualCameraDetected.hashCode ^
      unknownDeviceState.hashCode ^
      findings.hashCode ^
      hardFindings.hashCode ^
      warningFindings.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeSystemSecurityReviewResult &&
          runtimeType == other.runtimeType &&
          ready == other.ready &&
          platformSupported == other.platformSupported &&
          bluetoothDetected == other.bluetoothDetected &&
          externalAudioDetected == other.externalAudioDetected &&
          usbRiskDetected == other.usbRiskDetected &&
          virtualizationDetected == other.virtualizationDetected &&
          virtualizationWarningDetected ==
              other.virtualizationWarningDetected &&
          containerDetected == other.containerDetected &&
          virtualCameraDetected == other.virtualCameraDetected &&
          unknownDeviceState == other.unknownDeviceState &&
          findings == other.findings &&
          hardFindings == other.hardFindings &&
          warningFindings == other.warningFindings &&
          message == other.message;
}
