// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/evidence_vault.dart';
import 'api/proctoring.dart';
import 'api/system_security.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class BrainCoreApiApiImplPlatform
    extends BaseApiImpl<BrainCoreApiWire> {
  BrainCoreApiApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AcousticAnalysisDecision dco_decode_acoustic_analysis_decision(dynamic raw);

  @protected
  AcousticSampleDecision dco_decode_acoustic_sample_decision(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  GazeHeadPoseDecision dco_decode_box_autoadd_gaze_head_pose_decision(
    dynamic raw,
  );

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  EnvironmentFrameDecision dco_decode_environment_frame_decision(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FaceAnalysisDecision dco_decode_face_analysis_decision(dynamic raw);

  @protected
  GazeHeadPoseDecision dco_decode_gaze_head_pose_decision(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MotionAnalysisDecision dco_decode_motion_analysis_decision(dynamic raw);

  @protected
  NativeSystemSecurityReviewResult
  dco_decode_native_system_security_review_result(dynamic raw);

  @protected
  GazeHeadPoseDecision? dco_decode_opt_box_autoadd_gaze_head_pose_decision(
    dynamic raw,
  );

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  RotationAnalysisDecision dco_decode_rotation_analysis_decision(dynamic raw);

  @protected
  ScanFrameDecision dco_decode_scan_frame_decision(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VisionModelStatus dco_decode_vision_model_status(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AcousticAnalysisDecision sse_decode_acoustic_analysis_decision(
    SseDeserializer deserializer,
  );

  @protected
  AcousticSampleDecision sse_decode_acoustic_sample_decision(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  GazeHeadPoseDecision sse_decode_box_autoadd_gaze_head_pose_decision(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  EnvironmentFrameDecision sse_decode_environment_frame_decision(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FaceAnalysisDecision sse_decode_face_analysis_decision(
    SseDeserializer deserializer,
  );

  @protected
  GazeHeadPoseDecision sse_decode_gaze_head_pose_decision(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MotionAnalysisDecision sse_decode_motion_analysis_decision(
    SseDeserializer deserializer,
  );

  @protected
  NativeSystemSecurityReviewResult
  sse_decode_native_system_security_review_result(SseDeserializer deserializer);

  @protected
  GazeHeadPoseDecision? sse_decode_opt_box_autoadd_gaze_head_pose_decision(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  RotationAnalysisDecision sse_decode_rotation_analysis_decision(
    SseDeserializer deserializer,
  );

  @protected
  ScanFrameDecision sse_decode_scan_frame_decision(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VisionModelStatus sse_decode_vision_model_status(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_acoustic_analysis_decision(
    AcousticAnalysisDecision self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_acoustic_sample_decision(
    AcousticSampleDecision self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_gaze_head_pose_decision(
    GazeHeadPoseDecision self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_environment_frame_decision(
    EnvironmentFrameDecision self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_face_analysis_decision(
    FaceAnalysisDecision self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_gaze_head_pose_decision(
    GazeHeadPoseDecision self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_motion_analysis_decision(
    MotionAnalysisDecision self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_system_security_review_result(
    NativeSystemSecurityReviewResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_gaze_head_pose_decision(
    GazeHeadPoseDecision? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rotation_analysis_decision(
    RotationAnalysisDecision self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_scan_frame_decision(
    ScanFrameDecision self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_vision_model_status(
    VisionModelStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class BrainCoreApiWire implements BaseWire {
  BrainCoreApiWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external BrainCoreApiWasmModule get wasmModule;

@JS()
@anonymous
extension type BrainCoreApiWasmModule._(JSObject _) implements JSObject {}
