// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/attempt_recovery.dart';
import 'api/audio_intelligence.dart';
import 'api/evidence_vault.dart';
import 'api/lockdown.dart';
import 'api/proctoring.dart';
import 'api/system_security.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class BrainCoreApi
    extends
        BaseEntrypoint<BrainCoreApiApi, BrainCoreApiApiImpl, BrainCoreApiWire> {
  @internal
  static final instance = BrainCoreApi._();

  BrainCoreApi._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    BrainCoreApiApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required BrainCoreApiApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<BrainCoreApiApiImpl, BrainCoreApiWire>
  get apiImplConstructor => BrainCoreApiApiImpl.new;

  @override
  WireConstructor<BrainCoreApiWire> get wireConstructor =>
      BrainCoreApiWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1495641733;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'brain_core',
        ioDirectory: 'native/brain_core/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class BrainCoreApiApi extends BaseApi {
  AcousticAnalysisDecision crateApiProctoringAnalyzeAcousticChunk({
    required List<int> pcm16Bytes,
    required double lossThresholdDbfs,
    required int lossStreak,
    required int lossSamplesToTrigger,
    required double speechThresholdDbfs,
    required int speechStreak,
    required int speechSamplesToTrigger,
    required PlatformInt64 lastSpeechStrikeAtMs,
    required PlatformInt64 speechCooldownMs,
    required PlatformInt64 nowMs,
  });

  NativeAudioIntelligenceResult? crateApiAudioIntelligenceAnalyzeAudioPcm16({
    required List<int> bytes,
    required int sampleRate,
    String? previousFingerprint,
  });

  EnvironmentFrameDecision crateApiProctoringAnalyzeEnvironmentFrame({
    required List<String> objectLabels,
    required double lightingScore,
    required bool rotationCovered,
    required List<String> forbiddenKeywords,
  });

  FaceAnalysisDecision crateApiProctoringAnalyzeFaceState({
    required int faceCount,
    required bool includeGaze,
    required double yaw,
    required double pitch,
    required PlatformInt64 nowMs,
    required PlatformInt64 lastMultiFaceStrikeAtMs,
    required PlatformInt64 multiFaceCooldownMs,
    PlatformInt64? gazeAwayStartedAtMs,
    required PlatformInt64 gazeAwayDurationMs,
    required PlatformInt64 lastGazeWarningAtMs,
    required PlatformInt64 gazeWarningCooldownMs,
    required double yawThreshold,
    required double pitchThreshold,
  });

  GazeHeadPoseDecision? crateApiProctoringAnalyzeGazeHeadPoseFrame({
    required List<int> plane0Bytes,
    required int width,
    required int height,
    required int bytesPerRow,
    required double previousYaw,
    required double previousPitch,
    required double previousRoll,
  });

  MotionAnalysisDecision crateApiProctoringAnalyzeMotionSample({
    required double x,
    required double y,
    required double z,
    required double xThreshold,
    required double yThreshold,
    required double zThreshold,
    required PlatformInt64 nowMs,
    required PlatformInt64 lastViolationAtMs,
    required PlatformInt64 cooldownMs,
    required PlatformInt64 windowStartMs,
    required PlatformInt64 windowMs,
    required int burstCount,
    required int burstThreshold,
  });

  ScanFrameDecision crateApiProctoringAnalyzeScanFrame({
    required List<int> plane0Bytes,
    required int width,
    required int height,
    required int bytesPerRow,
    required String pixelFormat,
  });

  NativeSecureLockdownReviewResult crateApiLockdownAnalyzeSecureLockdownReport({
    required String platformName,
    required String processReport,
    int? displayCount,
  });

  NativeSystemSecurityReviewResult
  crateApiSystemSecurityAnalyzeSystemSecurityReport({
    required String report,
    required String platformName,
  });

  String crateApiAttemptRecoveryAttemptChecksum({required String payloadJson});

  void crateApiProctoringClearVisionModel();

  Future<int?> crateApiLockdownCollectLockdownDisplayCount({
    required String platformName,
  });

  Future<String> crateApiLockdownCollectLockdownProcessReport({
    required String platformName,
  });

  Future<String> crateApiSystemSecurityCollectSystemSecurityReport({
    required String platformName,
  });

  VisionModelStatus crateApiProctoringCurrentVisionModelStatus();

  double crateApiProctoringEstimateLightingFromLuma({
    required List<int> lumaBytes,
    required int sampleStride,
  });

  String crateApiEvidenceVaultEvidenceSha256Hex({required List<int> bytes});

  VisionModelStatus crateApiProctoringLoadVisionModel({
    required String manifestJson,
    required List<int> modelBytes,
  });

  AcousticSampleDecision crateApiProctoringProcessAcousticSample({
    required double dbfs,
    required double lossThresholdDbfs,
    required int lossStreak,
    required int lossSamplesToTrigger,
  });

  String crateApiEvidenceVaultReadEvidenceBundle({
    required String baseDir,
    required String studentId,
    required String examId,
    required String attemptId,
  });

  Future<NativeSecureLockdownReviewResult>
  crateApiLockdownRunSecureLockdownReview({required String platformName});

  Future<NativeSystemSecurityReviewResult>
  crateApiSystemSecurityRunSystemSecurityReview({required String platformName});

  String crateApiEvidenceVaultSaveEvidenceBytes({
    required String baseDir,
    required String studentId,
    required String examId,
    required String attemptId,
    required String eventType,
    required String fileType,
    required String reviewReason,
    required List<int> bytes,
    required String metadataJson,
  });

  RotationAnalysisDecision crateApiProctoringUpdateRotationProgress({
    required double x,
    required double y,
    required double z,
    required double accumulated,
    required double currentProgress,
    required double deltaScale,
    required double minDelta,
    required double targetAccumulated,
  });

  NativeAttemptRecoveryCheck crateApiAttemptRecoveryVerifyAttemptSnapshot({
    required String payloadJson,
    required String checksum,
    required String recoveredFrom,
  });
}

class BrainCoreApiApiImpl extends BrainCoreApiApiImplPlatform
    implements BrainCoreApiApi {
  BrainCoreApiApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  AcousticAnalysisDecision crateApiProctoringAnalyzeAcousticChunk({
    required List<int> pcm16Bytes,
    required double lossThresholdDbfs,
    required int lossStreak,
    required int lossSamplesToTrigger,
    required double speechThresholdDbfs,
    required int speechStreak,
    required int speechSamplesToTrigger,
    required PlatformInt64 lastSpeechStrikeAtMs,
    required PlatformInt64 speechCooldownMs,
    required PlatformInt64 nowMs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(pcm16Bytes, serializer);
          sse_encode_f_64(lossThresholdDbfs, serializer);
          sse_encode_u_32(lossStreak, serializer);
          sse_encode_u_32(lossSamplesToTrigger, serializer);
          sse_encode_f_64(speechThresholdDbfs, serializer);
          sse_encode_u_32(speechStreak, serializer);
          sse_encode_u_32(speechSamplesToTrigger, serializer);
          sse_encode_i_64(lastSpeechStrikeAtMs, serializer);
          sse_encode_i_64(speechCooldownMs, serializer);
          sse_encode_i_64(nowMs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_acoustic_analysis_decision,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProctoringAnalyzeAcousticChunkConstMeta,
        argValues: [
          pcm16Bytes,
          lossThresholdDbfs,
          lossStreak,
          lossSamplesToTrigger,
          speechThresholdDbfs,
          speechStreak,
          speechSamplesToTrigger,
          lastSpeechStrikeAtMs,
          speechCooldownMs,
          nowMs,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProctoringAnalyzeAcousticChunkConstMeta =>
      const TaskConstMeta(
        debugName: "analyze_acoustic_chunk",
        argNames: [
          "pcm16Bytes",
          "lossThresholdDbfs",
          "lossStreak",
          "lossSamplesToTrigger",
          "speechThresholdDbfs",
          "speechStreak",
          "speechSamplesToTrigger",
          "lastSpeechStrikeAtMs",
          "speechCooldownMs",
          "nowMs",
        ],
      );

  @override
  NativeAudioIntelligenceResult? crateApiAudioIntelligenceAnalyzeAudioPcm16({
    required List<int> bytes,
    required int sampleRate,
    String? previousFingerprint,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_i_32(sampleRate, serializer);
          sse_encode_opt_String(previousFingerprint, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_opt_box_autoadd_native_audio_intelligence_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioIntelligenceAnalyzeAudioPcm16ConstMeta,
        argValues: [bytes, sampleRate, previousFingerprint],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioIntelligenceAnalyzeAudioPcm16ConstMeta =>
      const TaskConstMeta(
        debugName: "analyze_audio_pcm16",
        argNames: ["bytes", "sampleRate", "previousFingerprint"],
      );

  @override
  EnvironmentFrameDecision crateApiProctoringAnalyzeEnvironmentFrame({
    required List<String> objectLabels,
    required double lightingScore,
    required bool rotationCovered,
    required List<String> forbiddenKeywords,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(objectLabels, serializer);
          sse_encode_f_64(lightingScore, serializer);
          sse_encode_bool(rotationCovered, serializer);
          sse_encode_list_String(forbiddenKeywords, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_environment_frame_decision,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProctoringAnalyzeEnvironmentFrameConstMeta,
        argValues: [
          objectLabels,
          lightingScore,
          rotationCovered,
          forbiddenKeywords,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProctoringAnalyzeEnvironmentFrameConstMeta =>
      const TaskConstMeta(
        debugName: "analyze_environment_frame",
        argNames: [
          "objectLabels",
          "lightingScore",
          "rotationCovered",
          "forbiddenKeywords",
        ],
      );

  @override
  FaceAnalysisDecision crateApiProctoringAnalyzeFaceState({
    required int faceCount,
    required bool includeGaze,
    required double yaw,
    required double pitch,
    required PlatformInt64 nowMs,
    required PlatformInt64 lastMultiFaceStrikeAtMs,
    required PlatformInt64 multiFaceCooldownMs,
    PlatformInt64? gazeAwayStartedAtMs,
    required PlatformInt64 gazeAwayDurationMs,
    required PlatformInt64 lastGazeWarningAtMs,
    required PlatformInt64 gazeWarningCooldownMs,
    required double yawThreshold,
    required double pitchThreshold,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(faceCount, serializer);
          sse_encode_bool(includeGaze, serializer);
          sse_encode_f_64(yaw, serializer);
          sse_encode_f_64(pitch, serializer);
          sse_encode_i_64(nowMs, serializer);
          sse_encode_i_64(lastMultiFaceStrikeAtMs, serializer);
          sse_encode_i_64(multiFaceCooldownMs, serializer);
          sse_encode_opt_box_autoadd_i_64(gazeAwayStartedAtMs, serializer);
          sse_encode_i_64(gazeAwayDurationMs, serializer);
          sse_encode_i_64(lastGazeWarningAtMs, serializer);
          sse_encode_i_64(gazeWarningCooldownMs, serializer);
          sse_encode_f_64(yawThreshold, serializer);
          sse_encode_f_64(pitchThreshold, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_face_analysis_decision,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProctoringAnalyzeFaceStateConstMeta,
        argValues: [
          faceCount,
          includeGaze,
          yaw,
          pitch,
          nowMs,
          lastMultiFaceStrikeAtMs,
          multiFaceCooldownMs,
          gazeAwayStartedAtMs,
          gazeAwayDurationMs,
          lastGazeWarningAtMs,
          gazeWarningCooldownMs,
          yawThreshold,
          pitchThreshold,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProctoringAnalyzeFaceStateConstMeta =>
      const TaskConstMeta(
        debugName: "analyze_face_state",
        argNames: [
          "faceCount",
          "includeGaze",
          "yaw",
          "pitch",
          "nowMs",
          "lastMultiFaceStrikeAtMs",
          "multiFaceCooldownMs",
          "gazeAwayStartedAtMs",
          "gazeAwayDurationMs",
          "lastGazeWarningAtMs",
          "gazeWarningCooldownMs",
          "yawThreshold",
          "pitchThreshold",
        ],
      );

  @override
  GazeHeadPoseDecision? crateApiProctoringAnalyzeGazeHeadPoseFrame({
    required List<int> plane0Bytes,
    required int width,
    required int height,
    required int bytesPerRow,
    required double previousYaw,
    required double previousPitch,
    required double previousRoll,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(plane0Bytes, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          sse_encode_u_32(bytesPerRow, serializer);
          sse_encode_f_64(previousYaw, serializer);
          sse_encode_f_64(previousPitch, serializer);
          sse_encode_f_64(previousRoll, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_gaze_head_pose_decision,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProctoringAnalyzeGazeHeadPoseFrameConstMeta,
        argValues: [
          plane0Bytes,
          width,
          height,
          bytesPerRow,
          previousYaw,
          previousPitch,
          previousRoll,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProctoringAnalyzeGazeHeadPoseFrameConstMeta =>
      const TaskConstMeta(
        debugName: "analyze_gaze_head_pose_frame",
        argNames: [
          "plane0Bytes",
          "width",
          "height",
          "bytesPerRow",
          "previousYaw",
          "previousPitch",
          "previousRoll",
        ],
      );

  @override
  MotionAnalysisDecision crateApiProctoringAnalyzeMotionSample({
    required double x,
    required double y,
    required double z,
    required double xThreshold,
    required double yThreshold,
    required double zThreshold,
    required PlatformInt64 nowMs,
    required PlatformInt64 lastViolationAtMs,
    required PlatformInt64 cooldownMs,
    required PlatformInt64 windowStartMs,
    required PlatformInt64 windowMs,
    required int burstCount,
    required int burstThreshold,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(x, serializer);
          sse_encode_f_64(y, serializer);
          sse_encode_f_64(z, serializer);
          sse_encode_f_64(xThreshold, serializer);
          sse_encode_f_64(yThreshold, serializer);
          sse_encode_f_64(zThreshold, serializer);
          sse_encode_i_64(nowMs, serializer);
          sse_encode_i_64(lastViolationAtMs, serializer);
          sse_encode_i_64(cooldownMs, serializer);
          sse_encode_i_64(windowStartMs, serializer);
          sse_encode_i_64(windowMs, serializer);
          sse_encode_u_32(burstCount, serializer);
          sse_encode_u_32(burstThreshold, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_motion_analysis_decision,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProctoringAnalyzeMotionSampleConstMeta,
        argValues: [
          x,
          y,
          z,
          xThreshold,
          yThreshold,
          zThreshold,
          nowMs,
          lastViolationAtMs,
          cooldownMs,
          windowStartMs,
          windowMs,
          burstCount,
          burstThreshold,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProctoringAnalyzeMotionSampleConstMeta =>
      const TaskConstMeta(
        debugName: "analyze_motion_sample",
        argNames: [
          "x",
          "y",
          "z",
          "xThreshold",
          "yThreshold",
          "zThreshold",
          "nowMs",
          "lastViolationAtMs",
          "cooldownMs",
          "windowStartMs",
          "windowMs",
          "burstCount",
          "burstThreshold",
        ],
      );

  @override
  ScanFrameDecision crateApiProctoringAnalyzeScanFrame({
    required List<int> plane0Bytes,
    required int width,
    required int height,
    required int bytesPerRow,
    required String pixelFormat,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(plane0Bytes, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          sse_encode_u_32(bytesPerRow, serializer);
          sse_encode_String(pixelFormat, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_scan_frame_decision,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProctoringAnalyzeScanFrameConstMeta,
        argValues: [plane0Bytes, width, height, bytesPerRow, pixelFormat],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProctoringAnalyzeScanFrameConstMeta =>
      const TaskConstMeta(
        debugName: "analyze_scan_frame",
        argNames: [
          "plane0Bytes",
          "width",
          "height",
          "bytesPerRow",
          "pixelFormat",
        ],
      );

  @override
  NativeSecureLockdownReviewResult crateApiLockdownAnalyzeSecureLockdownReport({
    required String platformName,
    required String processReport,
    int? displayCount,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(platformName, serializer);
          sse_encode_String(processReport, serializer);
          sse_encode_opt_box_autoadd_i_32(displayCount, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_native_secure_lockdown_review_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLockdownAnalyzeSecureLockdownReportConstMeta,
        argValues: [platformName, processReport, displayCount],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLockdownAnalyzeSecureLockdownReportConstMeta =>
      const TaskConstMeta(
        debugName: "analyze_secure_lockdown_report",
        argNames: ["platformName", "processReport", "displayCount"],
      );

  @override
  NativeSystemSecurityReviewResult
  crateApiSystemSecurityAnalyzeSystemSecurityReport({
    required String report,
    required String platformName,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(report, serializer);
          sse_encode_String(platformName, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_native_system_security_review_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSystemSecurityAnalyzeSystemSecurityReportConstMeta,
        argValues: [report, platformName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSystemSecurityAnalyzeSystemSecurityReportConstMeta =>
      const TaskConstMeta(
        debugName: "analyze_system_security_report",
        argNames: ["report", "platformName"],
      );

  @override
  String crateApiAttemptRecoveryAttemptChecksum({required String payloadJson}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(payloadJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAttemptRecoveryAttemptChecksumConstMeta,
        argValues: [payloadJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAttemptRecoveryAttemptChecksumConstMeta =>
      const TaskConstMeta(
        debugName: "attempt_checksum",
        argNames: ["payloadJson"],
      );

  @override
  void crateApiProctoringClearVisionModel() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProctoringClearVisionModelConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProctoringClearVisionModelConstMeta =>
      const TaskConstMeta(debugName: "clear_vision_model", argNames: []);

  @override
  Future<int?> crateApiLockdownCollectLockdownDisplayCount({
    required String platformName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(platformName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_i_32,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLockdownCollectLockdownDisplayCountConstMeta,
        argValues: [platformName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLockdownCollectLockdownDisplayCountConstMeta =>
      const TaskConstMeta(
        debugName: "collect_lockdown_display_count",
        argNames: ["platformName"],
      );

  @override
  Future<String> crateApiLockdownCollectLockdownProcessReport({
    required String platformName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(platformName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLockdownCollectLockdownProcessReportConstMeta,
        argValues: [platformName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLockdownCollectLockdownProcessReportConstMeta =>
      const TaskConstMeta(
        debugName: "collect_lockdown_process_report",
        argNames: ["platformName"],
      );

  @override
  Future<String> crateApiSystemSecurityCollectSystemSecurityReport({
    required String platformName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(platformName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSystemSecurityCollectSystemSecurityReportConstMeta,
        argValues: [platformName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSystemSecurityCollectSystemSecurityReportConstMeta =>
      const TaskConstMeta(
        debugName: "collect_system_security_report",
        argNames: ["platformName"],
      );

  @override
  VisionModelStatus crateApiProctoringCurrentVisionModelStatus() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_vision_model_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProctoringCurrentVisionModelStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProctoringCurrentVisionModelStatusConstMeta =>
      const TaskConstMeta(
        debugName: "current_vision_model_status",
        argNames: [],
      );

  @override
  double crateApiProctoringEstimateLightingFromLuma({
    required List<int> lumaBytes,
    required int sampleStride,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(lumaBytes, serializer);
          sse_encode_u_32(sampleStride, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProctoringEstimateLightingFromLumaConstMeta,
        argValues: [lumaBytes, sampleStride],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProctoringEstimateLightingFromLumaConstMeta =>
      const TaskConstMeta(
        debugName: "estimate_lighting_from_luma",
        argNames: ["lumaBytes", "sampleStride"],
      );

  @override
  String crateApiEvidenceVaultEvidenceSha256Hex({required List<int> bytes}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEvidenceVaultEvidenceSha256HexConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEvidenceVaultEvidenceSha256HexConstMeta =>
      const TaskConstMeta(
        debugName: "evidence_sha256_hex",
        argNames: ["bytes"],
      );

  @override
  VisionModelStatus crateApiProctoringLoadVisionModel({
    required String manifestJson,
    required List<int> modelBytes,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(manifestJson, serializer);
          sse_encode_list_prim_u_8_loose(modelBytes, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_vision_model_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProctoringLoadVisionModelConstMeta,
        argValues: [manifestJson, modelBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProctoringLoadVisionModelConstMeta =>
      const TaskConstMeta(
        debugName: "load_vision_model",
        argNames: ["manifestJson", "modelBytes"],
      );

  @override
  AcousticSampleDecision crateApiProctoringProcessAcousticSample({
    required double dbfs,
    required double lossThresholdDbfs,
    required int lossStreak,
    required int lossSamplesToTrigger,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(dbfs, serializer);
          sse_encode_f_64(lossThresholdDbfs, serializer);
          sse_encode_u_32(lossStreak, serializer);
          sse_encode_u_32(lossSamplesToTrigger, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_acoustic_sample_decision,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProctoringProcessAcousticSampleConstMeta,
        argValues: [dbfs, lossThresholdDbfs, lossStreak, lossSamplesToTrigger],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProctoringProcessAcousticSampleConstMeta =>
      const TaskConstMeta(
        debugName: "process_acoustic_sample",
        argNames: [
          "dbfs",
          "lossThresholdDbfs",
          "lossStreak",
          "lossSamplesToTrigger",
        ],
      );

  @override
  String crateApiEvidenceVaultReadEvidenceBundle({
    required String baseDir,
    required String studentId,
    required String examId,
    required String attemptId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseDir, serializer);
          sse_encode_String(studentId, serializer);
          sse_encode_String(examId, serializer);
          sse_encode_String(attemptId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiEvidenceVaultReadEvidenceBundleConstMeta,
        argValues: [baseDir, studentId, examId, attemptId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEvidenceVaultReadEvidenceBundleConstMeta =>
      const TaskConstMeta(
        debugName: "read_evidence_bundle",
        argNames: ["baseDir", "studentId", "examId", "attemptId"],
      );

  @override
  Future<NativeSecureLockdownReviewResult>
  crateApiLockdownRunSecureLockdownReview({required String platformName}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(platformName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_native_secure_lockdown_review_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLockdownRunSecureLockdownReviewConstMeta,
        argValues: [platformName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLockdownRunSecureLockdownReviewConstMeta =>
      const TaskConstMeta(
        debugName: "run_secure_lockdown_review",
        argNames: ["platformName"],
      );

  @override
  Future<NativeSystemSecurityReviewResult>
  crateApiSystemSecurityRunSystemSecurityReview({
    required String platformName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(platformName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_native_system_security_review_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSystemSecurityRunSystemSecurityReviewConstMeta,
        argValues: [platformName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSystemSecurityRunSystemSecurityReviewConstMeta =>
      const TaskConstMeta(
        debugName: "run_system_security_review",
        argNames: ["platformName"],
      );

  @override
  String crateApiEvidenceVaultSaveEvidenceBytes({
    required String baseDir,
    required String studentId,
    required String examId,
    required String attemptId,
    required String eventType,
    required String fileType,
    required String reviewReason,
    required List<int> bytes,
    required String metadataJson,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(baseDir, serializer);
          sse_encode_String(studentId, serializer);
          sse_encode_String(examId, serializer);
          sse_encode_String(attemptId, serializer);
          sse_encode_String(eventType, serializer);
          sse_encode_String(fileType, serializer);
          sse_encode_String(reviewReason, serializer);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_String(metadataJson, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiEvidenceVaultSaveEvidenceBytesConstMeta,
        argValues: [
          baseDir,
          studentId,
          examId,
          attemptId,
          eventType,
          fileType,
          reviewReason,
          bytes,
          metadataJson,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEvidenceVaultSaveEvidenceBytesConstMeta =>
      const TaskConstMeta(
        debugName: "save_evidence_bytes",
        argNames: [
          "baseDir",
          "studentId",
          "examId",
          "attemptId",
          "eventType",
          "fileType",
          "reviewReason",
          "bytes",
          "metadataJson",
        ],
      );

  @override
  RotationAnalysisDecision crateApiProctoringUpdateRotationProgress({
    required double x,
    required double y,
    required double z,
    required double accumulated,
    required double currentProgress,
    required double deltaScale,
    required double minDelta,
    required double targetAccumulated,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(x, serializer);
          sse_encode_f_64(y, serializer);
          sse_encode_f_64(z, serializer);
          sse_encode_f_64(accumulated, serializer);
          sse_encode_f_64(currentProgress, serializer);
          sse_encode_f_64(deltaScale, serializer);
          sse_encode_f_64(minDelta, serializer);
          sse_encode_f_64(targetAccumulated, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rotation_analysis_decision,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProctoringUpdateRotationProgressConstMeta,
        argValues: [
          x,
          y,
          z,
          accumulated,
          currentProgress,
          deltaScale,
          minDelta,
          targetAccumulated,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProctoringUpdateRotationProgressConstMeta =>
      const TaskConstMeta(
        debugName: "update_rotation_progress",
        argNames: [
          "x",
          "y",
          "z",
          "accumulated",
          "currentProgress",
          "deltaScale",
          "minDelta",
          "targetAccumulated",
        ],
      );

  @override
  NativeAttemptRecoveryCheck crateApiAttemptRecoveryVerifyAttemptSnapshot({
    required String payloadJson,
    required String checksum,
    required String recoveredFrom,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(payloadJson, serializer);
          sse_encode_String(checksum, serializer);
          sse_encode_String(recoveredFrom, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_native_attempt_recovery_check,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAttemptRecoveryVerifyAttemptSnapshotConstMeta,
        argValues: [payloadJson, checksum, recoveredFrom],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAttemptRecoveryVerifyAttemptSnapshotConstMeta =>
      const TaskConstMeta(
        debugName: "verify_attempt_snapshot",
        argNames: ["payloadJson", "checksum", "recoveredFrom"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AcousticAnalysisDecision dco_decode_acoustic_analysis_decision(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return AcousticAnalysisDecision(
      dbfs: dco_decode_f_64(arr[0]),
      updatedLossStreak: dco_decode_u_32(arr[1]),
      shouldTriggerScan: dco_decode_bool(arr[2]),
      normalizedTetherSignal: dco_decode_f_64(arr[3]),
      updatedSpeechStreak: dco_decode_u_32(arr[4]),
      shouldTriggerSpeech: dco_decode_bool(arr[5]),
      updatedLastSpeechStrikeAtMs: dco_decode_i_64(arr[6]),
    );
  }

  @protected
  AcousticSampleDecision dco_decode_acoustic_sample_decision(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return AcousticSampleDecision(
      updatedLossStreak: dco_decode_u_32(arr[0]),
      shouldTriggerScan: dco_decode_bool(arr[1]),
      normalizedTetherSignal: dco_decode_f_64(arr[2]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  GazeHeadPoseDecision dco_decode_box_autoadd_gaze_head_pose_decision(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_gaze_head_pose_decision(raw);
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  NativeAudioIntelligenceResult
  dco_decode_box_autoadd_native_audio_intelligence_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_native_audio_intelligence_result(raw);
  }

  @protected
  EnvironmentFrameDecision dco_decode_environment_frame_decision(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return EnvironmentFrameDecision(
      normalizedLightingScore: dco_decode_f_64(arr[0]),
      rotationConfirmed: dco_decode_bool(arr[1]),
      forbiddenObjects: dco_decode_list_String(arr[2]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FaceAnalysisDecision dco_decode_face_analysis_decision(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return FaceAnalysisDecision(
      shouldFlagMultiFace: dco_decode_bool(arr[0]),
      shouldWarnGaze: dco_decode_bool(arr[1]),
      updatedLastMultiFaceStrikeAtMs: dco_decode_i_64(arr[2]),
      updatedLastGazeWarningAtMs: dco_decode_i_64(arr[3]),
      updatedGazeAwayStartedAtMs: dco_decode_opt_box_autoadd_i_64(arr[4]),
    );
  }

  @protected
  GazeHeadPoseDecision dco_decode_gaze_head_pose_decision(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return GazeHeadPoseDecision(
      gazeX: dco_decode_f_64(arr[0]),
      gazeY: dco_decode_f_64(arr[1]),
      gazeZ: dco_decode_f_64(arr[2]),
      yawProxy: dco_decode_f_64(arr[3]),
      pitchProxy: dco_decode_f_64(arr[4]),
      rollProxy: dco_decode_f_64(arr[5]),
      confidence: dco_decode_f_64(arr[6]),
      stableHeadPose: dco_decode_bool(arr[7]),
      lookingAway: dco_decode_bool(arr[8]),
      label: dco_decode_String(arr[9]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<NativeLockdownFinding> dco_decode_list_native_lockdown_finding(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_native_lockdown_finding)
        .toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MotionAnalysisDecision dco_decode_motion_analysis_decision(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return MotionAnalysisDecision(
      moved: dco_decode_bool(arr[0]),
      shouldLogViolation: dco_decode_bool(arr[1]),
      shouldTriggerScan: dco_decode_bool(arr[2]),
      updatedLastViolationAtMs: dco_decode_i_64(arr[3]),
      updatedWindowStartMs: dco_decode_i_64(arr[4]),
      updatedBurstCount: dco_decode_u_32(arr[5]),
    );
  }

  @protected
  NativeAttemptRecoveryCheck dco_decode_native_attempt_recovery_check(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return NativeAttemptRecoveryCheck(
      checksum: dco_decode_String(arr[0]),
      checksumValid: dco_decode_bool(arr[1]),
      payloadJson: dco_decode_String(arr[2]),
      recoveredFrom: dco_decode_String(arr[3]),
    );
  }

  @protected
  NativeAudioIntelligenceResult dco_decode_native_audio_intelligence_result(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return NativeAudioIntelligenceResult(
      ready: dco_decode_bool(arr[0]),
      label: dco_decode_String(arr[1]),
      rms: dco_decode_f_64(arr[2]),
      peak: dco_decode_f_64(arr[3]),
      zeroCrossingRate: dco_decode_f_64(arr[4]),
      dynamicVariation: dco_decode_f_64(arr[5]),
      voiceConfidence: dco_decode_f_64(arr[6]),
      nearVoiceLikely: dco_decode_bool(arr[7]),
      possibleFarVoiceLikely: dco_decode_bool(arr[8]),
      allowedAmbientLikely: dco_decode_bool(arr[9]),
      repeatedFingerprint: dco_decode_bool(arr[10]),
      fingerprint: dco_decode_String(arr[11]),
    );
  }

  @protected
  NativeLockdownFinding dco_decode_native_lockdown_finding(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return NativeLockdownFinding(
      code: dco_decode_String(arr[0]),
      message: dco_decode_String(arr[1]),
      severity: dco_decode_String(arr[2]),
    );
  }

  @protected
  NativeSecureLockdownReviewResult
  dco_decode_native_secure_lockdown_review_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return NativeSecureLockdownReviewResult(
      ready: dco_decode_bool(arr[0]),
      platformSupported: dco_decode_bool(arr[1]),
      platformName: dco_decode_String(arr[2]),
      displayCount: dco_decode_opt_box_autoadd_i_32(arr[3]),
      prohibitedProcesses: dco_decode_list_String(arr[4]),
      findings: dco_decode_list_native_lockdown_finding(arr[5]),
    );
  }

  @protected
  NativeSystemSecurityReviewResult
  dco_decode_native_system_security_review_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 14)
      throw Exception('unexpected arr length: expect 14 but see ${arr.length}');
    return NativeSystemSecurityReviewResult(
      ready: dco_decode_bool(arr[0]),
      platformSupported: dco_decode_bool(arr[1]),
      bluetoothDetected: dco_decode_bool(arr[2]),
      externalAudioDetected: dco_decode_bool(arr[3]),
      usbRiskDetected: dco_decode_bool(arr[4]),
      virtualizationDetected: dco_decode_bool(arr[5]),
      virtualizationWarningDetected: dco_decode_bool(arr[6]),
      containerDetected: dco_decode_bool(arr[7]),
      virtualCameraDetected: dco_decode_bool(arr[8]),
      unknownDeviceState: dco_decode_bool(arr[9]),
      findings: dco_decode_list_String(arr[10]),
      hardFindings: dco_decode_list_String(arr[11]),
      warningFindings: dco_decode_list_String(arr[12]),
      message: dco_decode_String(arr[13]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  GazeHeadPoseDecision? dco_decode_opt_box_autoadd_gaze_head_pose_decision(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_gaze_head_pose_decision(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  NativeAudioIntelligenceResult?
  dco_decode_opt_box_autoadd_native_audio_intelligence_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_native_audio_intelligence_result(raw);
  }

  @protected
  RotationAnalysisDecision dco_decode_rotation_analysis_decision(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RotationAnalysisDecision(
      updatedAccumulated: dco_decode_f_64(arr[0]),
      updatedProgress: dco_decode_f_64(arr[1]),
      rotationConfirmed: dco_decode_bool(arr[2]),
    );
  }

  @protected
  ScanFrameDecision dco_decode_scan_frame_decision(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ScanFrameDecision(
      lightingScore: dco_decode_f_64(arr[0]),
      objectLabels: dco_decode_list_String(arr[1]),
      faceCount: dco_decode_u_32(arr[2]),
      estimatedYaw: dco_decode_f_64(arr[3]),
      estimatedPitch: dco_decode_f_64(arr[4]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VisionModelStatus dco_decode_vision_model_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return VisionModelStatus(
      loaded: dco_decode_bool(arr[0]),
      modelName: dco_decode_String(arr[1]),
      inputWidth: dco_decode_u_32(arr[2]),
      inputHeight: dco_decode_u_32(arr[3]),
      confidenceThreshold: dco_decode_f_64(arr[4]),
      labelCount: dco_decode_u_32(arr[5]),
      message: dco_decode_String(arr[6]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AcousticAnalysisDecision sse_decode_acoustic_analysis_decision(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_dbfs = sse_decode_f_64(deserializer);
    var var_updatedLossStreak = sse_decode_u_32(deserializer);
    var var_shouldTriggerScan = sse_decode_bool(deserializer);
    var var_normalizedTetherSignal = sse_decode_f_64(deserializer);
    var var_updatedSpeechStreak = sse_decode_u_32(deserializer);
    var var_shouldTriggerSpeech = sse_decode_bool(deserializer);
    var var_updatedLastSpeechStrikeAtMs = sse_decode_i_64(deserializer);
    return AcousticAnalysisDecision(
      dbfs: var_dbfs,
      updatedLossStreak: var_updatedLossStreak,
      shouldTriggerScan: var_shouldTriggerScan,
      normalizedTetherSignal: var_normalizedTetherSignal,
      updatedSpeechStreak: var_updatedSpeechStreak,
      shouldTriggerSpeech: var_shouldTriggerSpeech,
      updatedLastSpeechStrikeAtMs: var_updatedLastSpeechStrikeAtMs,
    );
  }

  @protected
  AcousticSampleDecision sse_decode_acoustic_sample_decision(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_updatedLossStreak = sse_decode_u_32(deserializer);
    var var_shouldTriggerScan = sse_decode_bool(deserializer);
    var var_normalizedTetherSignal = sse_decode_f_64(deserializer);
    return AcousticSampleDecision(
      updatedLossStreak: var_updatedLossStreak,
      shouldTriggerScan: var_shouldTriggerScan,
      normalizedTetherSignal: var_normalizedTetherSignal,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  GazeHeadPoseDecision sse_decode_box_autoadd_gaze_head_pose_decision(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_gaze_head_pose_decision(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  NativeAudioIntelligenceResult
  sse_decode_box_autoadd_native_audio_intelligence_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_native_audio_intelligence_result(deserializer));
  }

  @protected
  EnvironmentFrameDecision sse_decode_environment_frame_decision(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_normalizedLightingScore = sse_decode_f_64(deserializer);
    var var_rotationConfirmed = sse_decode_bool(deserializer);
    var var_forbiddenObjects = sse_decode_list_String(deserializer);
    return EnvironmentFrameDecision(
      normalizedLightingScore: var_normalizedLightingScore,
      rotationConfirmed: var_rotationConfirmed,
      forbiddenObjects: var_forbiddenObjects,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FaceAnalysisDecision sse_decode_face_analysis_decision(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_shouldFlagMultiFace = sse_decode_bool(deserializer);
    var var_shouldWarnGaze = sse_decode_bool(deserializer);
    var var_updatedLastMultiFaceStrikeAtMs = sse_decode_i_64(deserializer);
    var var_updatedLastGazeWarningAtMs = sse_decode_i_64(deserializer);
    var var_updatedGazeAwayStartedAtMs = sse_decode_opt_box_autoadd_i_64(
      deserializer,
    );
    return FaceAnalysisDecision(
      shouldFlagMultiFace: var_shouldFlagMultiFace,
      shouldWarnGaze: var_shouldWarnGaze,
      updatedLastMultiFaceStrikeAtMs: var_updatedLastMultiFaceStrikeAtMs,
      updatedLastGazeWarningAtMs: var_updatedLastGazeWarningAtMs,
      updatedGazeAwayStartedAtMs: var_updatedGazeAwayStartedAtMs,
    );
  }

  @protected
  GazeHeadPoseDecision sse_decode_gaze_head_pose_decision(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_gazeX = sse_decode_f_64(deserializer);
    var var_gazeY = sse_decode_f_64(deserializer);
    var var_gazeZ = sse_decode_f_64(deserializer);
    var var_yawProxy = sse_decode_f_64(deserializer);
    var var_pitchProxy = sse_decode_f_64(deserializer);
    var var_rollProxy = sse_decode_f_64(deserializer);
    var var_confidence = sse_decode_f_64(deserializer);
    var var_stableHeadPose = sse_decode_bool(deserializer);
    var var_lookingAway = sse_decode_bool(deserializer);
    var var_label = sse_decode_String(deserializer);
    return GazeHeadPoseDecision(
      gazeX: var_gazeX,
      gazeY: var_gazeY,
      gazeZ: var_gazeZ,
      yawProxy: var_yawProxy,
      pitchProxy: var_pitchProxy,
      rollProxy: var_rollProxy,
      confidence: var_confidence,
      stableHeadPose: var_stableHeadPose,
      lookingAway: var_lookingAway,
      label: var_label,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<NativeLockdownFinding> sse_decode_list_native_lockdown_finding(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NativeLockdownFinding>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_native_lockdown_finding(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MotionAnalysisDecision sse_decode_motion_analysis_decision(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_moved = sse_decode_bool(deserializer);
    var var_shouldLogViolation = sse_decode_bool(deserializer);
    var var_shouldTriggerScan = sse_decode_bool(deserializer);
    var var_updatedLastViolationAtMs = sse_decode_i_64(deserializer);
    var var_updatedWindowStartMs = sse_decode_i_64(deserializer);
    var var_updatedBurstCount = sse_decode_u_32(deserializer);
    return MotionAnalysisDecision(
      moved: var_moved,
      shouldLogViolation: var_shouldLogViolation,
      shouldTriggerScan: var_shouldTriggerScan,
      updatedLastViolationAtMs: var_updatedLastViolationAtMs,
      updatedWindowStartMs: var_updatedWindowStartMs,
      updatedBurstCount: var_updatedBurstCount,
    );
  }

  @protected
  NativeAttemptRecoveryCheck sse_decode_native_attempt_recovery_check(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_checksum = sse_decode_String(deserializer);
    var var_checksumValid = sse_decode_bool(deserializer);
    var var_payloadJson = sse_decode_String(deserializer);
    var var_recoveredFrom = sse_decode_String(deserializer);
    return NativeAttemptRecoveryCheck(
      checksum: var_checksum,
      checksumValid: var_checksumValid,
      payloadJson: var_payloadJson,
      recoveredFrom: var_recoveredFrom,
    );
  }

  @protected
  NativeAudioIntelligenceResult sse_decode_native_audio_intelligence_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ready = sse_decode_bool(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_rms = sse_decode_f_64(deserializer);
    var var_peak = sse_decode_f_64(deserializer);
    var var_zeroCrossingRate = sse_decode_f_64(deserializer);
    var var_dynamicVariation = sse_decode_f_64(deserializer);
    var var_voiceConfidence = sse_decode_f_64(deserializer);
    var var_nearVoiceLikely = sse_decode_bool(deserializer);
    var var_possibleFarVoiceLikely = sse_decode_bool(deserializer);
    var var_allowedAmbientLikely = sse_decode_bool(deserializer);
    var var_repeatedFingerprint = sse_decode_bool(deserializer);
    var var_fingerprint = sse_decode_String(deserializer);
    return NativeAudioIntelligenceResult(
      ready: var_ready,
      label: var_label,
      rms: var_rms,
      peak: var_peak,
      zeroCrossingRate: var_zeroCrossingRate,
      dynamicVariation: var_dynamicVariation,
      voiceConfidence: var_voiceConfidence,
      nearVoiceLikely: var_nearVoiceLikely,
      possibleFarVoiceLikely: var_possibleFarVoiceLikely,
      allowedAmbientLikely: var_allowedAmbientLikely,
      repeatedFingerprint: var_repeatedFingerprint,
      fingerprint: var_fingerprint,
    );
  }

  @protected
  NativeLockdownFinding sse_decode_native_lockdown_finding(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_severity = sse_decode_String(deserializer);
    return NativeLockdownFinding(
      code: var_code,
      message: var_message,
      severity: var_severity,
    );
  }

  @protected
  NativeSecureLockdownReviewResult
  sse_decode_native_secure_lockdown_review_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ready = sse_decode_bool(deserializer);
    var var_platformSupported = sse_decode_bool(deserializer);
    var var_platformName = sse_decode_String(deserializer);
    var var_displayCount = sse_decode_opt_box_autoadd_i_32(deserializer);
    var var_prohibitedProcesses = sse_decode_list_String(deserializer);
    var var_findings = sse_decode_list_native_lockdown_finding(deserializer);
    return NativeSecureLockdownReviewResult(
      ready: var_ready,
      platformSupported: var_platformSupported,
      platformName: var_platformName,
      displayCount: var_displayCount,
      prohibitedProcesses: var_prohibitedProcesses,
      findings: var_findings,
    );
  }

  @protected
  NativeSystemSecurityReviewResult
  sse_decode_native_system_security_review_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ready = sse_decode_bool(deserializer);
    var var_platformSupported = sse_decode_bool(deserializer);
    var var_bluetoothDetected = sse_decode_bool(deserializer);
    var var_externalAudioDetected = sse_decode_bool(deserializer);
    var var_usbRiskDetected = sse_decode_bool(deserializer);
    var var_virtualizationDetected = sse_decode_bool(deserializer);
    var var_virtualizationWarningDetected = sse_decode_bool(deserializer);
    var var_containerDetected = sse_decode_bool(deserializer);
    var var_virtualCameraDetected = sse_decode_bool(deserializer);
    var var_unknownDeviceState = sse_decode_bool(deserializer);
    var var_findings = sse_decode_list_String(deserializer);
    var var_hardFindings = sse_decode_list_String(deserializer);
    var var_warningFindings = sse_decode_list_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    return NativeSystemSecurityReviewResult(
      ready: var_ready,
      platformSupported: var_platformSupported,
      bluetoothDetected: var_bluetoothDetected,
      externalAudioDetected: var_externalAudioDetected,
      usbRiskDetected: var_usbRiskDetected,
      virtualizationDetected: var_virtualizationDetected,
      virtualizationWarningDetected: var_virtualizationWarningDetected,
      containerDetected: var_containerDetected,
      virtualCameraDetected: var_virtualCameraDetected,
      unknownDeviceState: var_unknownDeviceState,
      findings: var_findings,
      hardFindings: var_hardFindings,
      warningFindings: var_warningFindings,
      message: var_message,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  GazeHeadPoseDecision? sse_decode_opt_box_autoadd_gaze_head_pose_decision(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_gaze_head_pose_decision(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  NativeAudioIntelligenceResult?
  sse_decode_opt_box_autoadd_native_audio_intelligence_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_native_audio_intelligence_result(
        deserializer,
      ));
    } else {
      return null;
    }
  }

  @protected
  RotationAnalysisDecision sse_decode_rotation_analysis_decision(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_updatedAccumulated = sse_decode_f_64(deserializer);
    var var_updatedProgress = sse_decode_f_64(deserializer);
    var var_rotationConfirmed = sse_decode_bool(deserializer);
    return RotationAnalysisDecision(
      updatedAccumulated: var_updatedAccumulated,
      updatedProgress: var_updatedProgress,
      rotationConfirmed: var_rotationConfirmed,
    );
  }

  @protected
  ScanFrameDecision sse_decode_scan_frame_decision(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_lightingScore = sse_decode_f_64(deserializer);
    var var_objectLabels = sse_decode_list_String(deserializer);
    var var_faceCount = sse_decode_u_32(deserializer);
    var var_estimatedYaw = sse_decode_f_64(deserializer);
    var var_estimatedPitch = sse_decode_f_64(deserializer);
    return ScanFrameDecision(
      lightingScore: var_lightingScore,
      objectLabels: var_objectLabels,
      faceCount: var_faceCount,
      estimatedYaw: var_estimatedYaw,
      estimatedPitch: var_estimatedPitch,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VisionModelStatus sse_decode_vision_model_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_loaded = sse_decode_bool(deserializer);
    var var_modelName = sse_decode_String(deserializer);
    var var_inputWidth = sse_decode_u_32(deserializer);
    var var_inputHeight = sse_decode_u_32(deserializer);
    var var_confidenceThreshold = sse_decode_f_64(deserializer);
    var var_labelCount = sse_decode_u_32(deserializer);
    var var_message = sse_decode_String(deserializer);
    return VisionModelStatus(
      loaded: var_loaded,
      modelName: var_modelName,
      inputWidth: var_inputWidth,
      inputHeight: var_inputHeight,
      confidenceThreshold: var_confidenceThreshold,
      labelCount: var_labelCount,
      message: var_message,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_acoustic_analysis_decision(
    AcousticAnalysisDecision self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.dbfs, serializer);
    sse_encode_u_32(self.updatedLossStreak, serializer);
    sse_encode_bool(self.shouldTriggerScan, serializer);
    sse_encode_f_64(self.normalizedTetherSignal, serializer);
    sse_encode_u_32(self.updatedSpeechStreak, serializer);
    sse_encode_bool(self.shouldTriggerSpeech, serializer);
    sse_encode_i_64(self.updatedLastSpeechStrikeAtMs, serializer);
  }

  @protected
  void sse_encode_acoustic_sample_decision(
    AcousticSampleDecision self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.updatedLossStreak, serializer);
    sse_encode_bool(self.shouldTriggerScan, serializer);
    sse_encode_f_64(self.normalizedTetherSignal, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_gaze_head_pose_decision(
    GazeHeadPoseDecision self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_gaze_head_pose_decision(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_native_audio_intelligence_result(
    NativeAudioIntelligenceResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_native_audio_intelligence_result(self, serializer);
  }

  @protected
  void sse_encode_environment_frame_decision(
    EnvironmentFrameDecision self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.normalizedLightingScore, serializer);
    sse_encode_bool(self.rotationConfirmed, serializer);
    sse_encode_list_String(self.forbiddenObjects, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_face_analysis_decision(
    FaceAnalysisDecision self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.shouldFlagMultiFace, serializer);
    sse_encode_bool(self.shouldWarnGaze, serializer);
    sse_encode_i_64(self.updatedLastMultiFaceStrikeAtMs, serializer);
    sse_encode_i_64(self.updatedLastGazeWarningAtMs, serializer);
    sse_encode_opt_box_autoadd_i_64(
      self.updatedGazeAwayStartedAtMs,
      serializer,
    );
  }

  @protected
  void sse_encode_gaze_head_pose_decision(
    GazeHeadPoseDecision self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.gazeX, serializer);
    sse_encode_f_64(self.gazeY, serializer);
    sse_encode_f_64(self.gazeZ, serializer);
    sse_encode_f_64(self.yawProxy, serializer);
    sse_encode_f_64(self.pitchProxy, serializer);
    sse_encode_f_64(self.rollProxy, serializer);
    sse_encode_f_64(self.confidence, serializer);
    sse_encode_bool(self.stableHeadPose, serializer);
    sse_encode_bool(self.lookingAway, serializer);
    sse_encode_String(self.label, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_native_lockdown_finding(
    List<NativeLockdownFinding> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_native_lockdown_finding(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_motion_analysis_decision(
    MotionAnalysisDecision self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.moved, serializer);
    sse_encode_bool(self.shouldLogViolation, serializer);
    sse_encode_bool(self.shouldTriggerScan, serializer);
    sse_encode_i_64(self.updatedLastViolationAtMs, serializer);
    sse_encode_i_64(self.updatedWindowStartMs, serializer);
    sse_encode_u_32(self.updatedBurstCount, serializer);
  }

  @protected
  void sse_encode_native_attempt_recovery_check(
    NativeAttemptRecoveryCheck self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.checksum, serializer);
    sse_encode_bool(self.checksumValid, serializer);
    sse_encode_String(self.payloadJson, serializer);
    sse_encode_String(self.recoveredFrom, serializer);
  }

  @protected
  void sse_encode_native_audio_intelligence_result(
    NativeAudioIntelligenceResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ready, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_f_64(self.rms, serializer);
    sse_encode_f_64(self.peak, serializer);
    sse_encode_f_64(self.zeroCrossingRate, serializer);
    sse_encode_f_64(self.dynamicVariation, serializer);
    sse_encode_f_64(self.voiceConfidence, serializer);
    sse_encode_bool(self.nearVoiceLikely, serializer);
    sse_encode_bool(self.possibleFarVoiceLikely, serializer);
    sse_encode_bool(self.allowedAmbientLikely, serializer);
    sse_encode_bool(self.repeatedFingerprint, serializer);
    sse_encode_String(self.fingerprint, serializer);
  }

  @protected
  void sse_encode_native_lockdown_finding(
    NativeLockdownFinding self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.code, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_String(self.severity, serializer);
  }

  @protected
  void sse_encode_native_secure_lockdown_review_result(
    NativeSecureLockdownReviewResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ready, serializer);
    sse_encode_bool(self.platformSupported, serializer);
    sse_encode_String(self.platformName, serializer);
    sse_encode_opt_box_autoadd_i_32(self.displayCount, serializer);
    sse_encode_list_String(self.prohibitedProcesses, serializer);
    sse_encode_list_native_lockdown_finding(self.findings, serializer);
  }

  @protected
  void sse_encode_native_system_security_review_result(
    NativeSystemSecurityReviewResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ready, serializer);
    sse_encode_bool(self.platformSupported, serializer);
    sse_encode_bool(self.bluetoothDetected, serializer);
    sse_encode_bool(self.externalAudioDetected, serializer);
    sse_encode_bool(self.usbRiskDetected, serializer);
    sse_encode_bool(self.virtualizationDetected, serializer);
    sse_encode_bool(self.virtualizationWarningDetected, serializer);
    sse_encode_bool(self.containerDetected, serializer);
    sse_encode_bool(self.virtualCameraDetected, serializer);
    sse_encode_bool(self.unknownDeviceState, serializer);
    sse_encode_list_String(self.findings, serializer);
    sse_encode_list_String(self.hardFindings, serializer);
    sse_encode_list_String(self.warningFindings, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_gaze_head_pose_decision(
    GazeHeadPoseDecision? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_gaze_head_pose_decision(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_native_audio_intelligence_result(
    NativeAudioIntelligenceResult? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_native_audio_intelligence_result(self, serializer);
    }
  }

  @protected
  void sse_encode_rotation_analysis_decision(
    RotationAnalysisDecision self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.updatedAccumulated, serializer);
    sse_encode_f_64(self.updatedProgress, serializer);
    sse_encode_bool(self.rotationConfirmed, serializer);
  }

  @protected
  void sse_encode_scan_frame_decision(
    ScanFrameDecision self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.lightingScore, serializer);
    sse_encode_list_String(self.objectLabels, serializer);
    sse_encode_u_32(self.faceCount, serializer);
    sse_encode_f_64(self.estimatedYaw, serializer);
    sse_encode_f_64(self.estimatedPitch, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_vision_model_status(
    VisionModelStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.loaded, serializer);
    sse_encode_String(self.modelName, serializer);
    sse_encode_u_32(self.inputWidth, serializer);
    sse_encode_u_32(self.inputHeight, serializer);
    sse_encode_f_64(self.confidenceThreshold, serializer);
    sse_encode_u_32(self.labelCount, serializer);
    sse_encode_String(self.message, serializer);
  }
}
