// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/ai_action_policy.dart';
import 'api/air_board.dart';
import 'api/attempt_recovery.dart';
import 'api/audio_intelligence.dart';
import 'api/evidence_vault.dart';
import 'api/exam_behavior.dart';
import 'api/eye_intelligence.dart';
import 'api/face_verification.dart';
import 'api/gaze_calibration.dart';
import 'api/hand_air_board.dart';
import 'api/hand_gesture.dart';
import 'api/hand_landmark_runtime.dart';
import 'api/hand_vision.dart';
import 'api/lockdown.dart';
import 'api/native_vision.dart';
import 'api/proctoring.dart';
import 'api/system_security.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class BrainCoreApiApiImplPlatform
    extends BaseApiImpl<BrainCoreApiWire> {
  BrainCoreApiApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AcousticAnalysisDecision dco_decode_acoustic_analysis_decision(dynamic raw);

  @protected
  AcousticSampleDecision dco_decode_acoustic_sample_decision(dynamic raw);

  @protected
  AiActionAuthorization dco_decode_ai_action_authorization(dynamic raw);

  @protected
  AirBoardActivitySummary dco_decode_air_board_activity_summary(dynamic raw);

  @protected
  AirBoardContext dco_decode_air_board_context(dynamic raw);

  @protected
  AirBoardStroke dco_decode_air_board_stroke(dynamic raw);

  @protected
  AirBoardStrokePoint dco_decode_air_board_stroke_point(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AirBoardActivitySummary dco_decode_box_autoadd_air_board_activity_summary(
    dynamic raw,
  );

  @protected
  AirBoardContext dco_decode_box_autoadd_air_board_context(dynamic raw);

  @protected
  ExamBehaviourContext dco_decode_box_autoadd_exam_behaviour_context(
    dynamic raw,
  );

  @protected
  EyeRegionSignal dco_decode_box_autoadd_eye_region_signal(dynamic raw);

  @protected
  GazeCalibrationProfile dco_decode_box_autoadd_gaze_calibration_profile(
    dynamic raw,
  );

  @protected
  GazeHeadPoseDecision dco_decode_box_autoadd_gaze_head_pose_decision(
    dynamic raw,
  );

  @protected
  HandAirBoardContext dco_decode_box_autoadd_hand_air_board_context(
    dynamic raw,
  );

  @protected
  HandGestureInput dco_decode_box_autoadd_hand_gesture_input(dynamic raw);

  @protected
  HandVisionZones dco_decode_box_autoadd_hand_vision_zones(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  NativeAudioIntelligenceResult
  dco_decode_box_autoadd_native_audio_intelligence_result(dynamic raw);

  @protected
  EnvironmentFrameDecision dco_decode_environment_frame_decision(dynamic raw);

  @protected
  ExamBehaviourContext dco_decode_exam_behaviour_context(dynamic raw);

  @protected
  ExamBehaviourDecision dco_decode_exam_behaviour_decision(dynamic raw);

  @protected
  EyeIntelligenceResult dco_decode_eye_intelligence_result(dynamic raw);

  @protected
  EyeRegionSignal dco_decode_eye_region_signal(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FaceAnalysisDecision dco_decode_face_analysis_decision(dynamic raw);

  @protected
  FaceTemplateStatus dco_decode_face_template_status(dynamic raw);

  @protected
  FaceVerificationResult dco_decode_face_verification_result(dynamic raw);

  @protected
  GazeCalibrationProfile dco_decode_gaze_calibration_profile(dynamic raw);

  @protected
  GazeCalibrationSample dco_decode_gaze_calibration_sample(dynamic raw);

  @protected
  GazeHeadPoseDecision dco_decode_gaze_head_pose_decision(dynamic raw);

  @protected
  GazeZonePrediction dco_decode_gaze_zone_prediction(dynamic raw);

  @protected
  HandAirBoardContext dco_decode_hand_air_board_context(dynamic raw);

  @protected
  HandAirBoardDecision dco_decode_hand_air_board_decision(dynamic raw);

  @protected
  HandGestureInput dco_decode_hand_gesture_input(dynamic raw);

  @protected
  HandGestureResult dco_decode_hand_gesture_result(dynamic raw);

  @protected
  HandLandmarkInferenceResult dco_decode_hand_landmark_inference_result(
    dynamic raw,
  );

  @protected
  HandLandmarkModelStatus dco_decode_hand_landmark_model_status(dynamic raw);

  @protected
  HandLandmarkPoint dco_decode_hand_landmark_point(dynamic raw);

  @protected
  HandRegionSignal dco_decode_hand_region_signal(dynamic raw);

  @protected
  HandVisionModelStatus dco_decode_hand_vision_model_status(dynamic raw);

  @protected
  HandVisionResult dco_decode_hand_vision_result(dynamic raw);

  @protected
  HandVisionZones dco_decode_hand_vision_zones(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AirBoardStroke> dco_decode_list_air_board_stroke(dynamic raw);

  @protected
  List<AirBoardStrokePoint> dco_decode_list_air_board_stroke_point(dynamic raw);

  @protected
  List<GazeCalibrationSample> dco_decode_list_gaze_calibration_sample(
    dynamic raw,
  );

  @protected
  List<HandLandmarkPoint> dco_decode_list_hand_landmark_point(dynamic raw);

  @protected
  List<Float32List> dco_decode_list_list_prim_f_32_strict(dynamic raw);

  @protected
  List<NativeLockdownFinding> dco_decode_list_native_lockdown_finding(
    dynamic raw,
  );

  @protected
  List<NativeVisionDetection> dco_decode_list_native_vision_detection(
    dynamic raw,
  );

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MotionAnalysisDecision dco_decode_motion_analysis_decision(dynamic raw);

  @protected
  NativeAttemptRecoveryCheck dco_decode_native_attempt_recovery_check(
    dynamic raw,
  );

  @protected
  NativeAudioIntelligenceResult dco_decode_native_audio_intelligence_result(
    dynamic raw,
  );

  @protected
  NativeHeadPoseReviewResult dco_decode_native_head_pose_review_result(
    dynamic raw,
  );

  @protected
  NativeLockdownFinding dco_decode_native_lockdown_finding(dynamic raw);

  @protected
  NativeObjectReviewResult dco_decode_native_object_review_result(dynamic raw);

  @protected
  NativeSecureLockdownReviewResult
  dco_decode_native_secure_lockdown_review_result(dynamic raw);

  @protected
  NativeSystemSecurityReviewResult
  dco_decode_native_system_security_review_result(dynamic raw);

  @protected
  NativeVisionDetection dco_decode_native_vision_detection(dynamic raw);

  @protected
  NativeVisionFrameQuality dco_decode_native_vision_frame_quality(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  GazeHeadPoseDecision? dco_decode_opt_box_autoadd_gaze_head_pose_decision(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  NativeAudioIntelligenceResult?
  dco_decode_opt_box_autoadd_native_audio_intelligence_result(dynamic raw);

  @protected
  RotationAnalysisDecision dco_decode_rotation_analysis_decision(dynamic raw);

  @protected
  ScanFrameDecision dco_decode_scan_frame_decision(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VisionModelStatus dco_decode_vision_model_status(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AcousticAnalysisDecision sse_decode_acoustic_analysis_decision(
    SseDeserializer deserializer,
  );

  @protected
  AcousticSampleDecision sse_decode_acoustic_sample_decision(
    SseDeserializer deserializer,
  );

  @protected
  AiActionAuthorization sse_decode_ai_action_authorization(
    SseDeserializer deserializer,
  );

  @protected
  AirBoardActivitySummary sse_decode_air_board_activity_summary(
    SseDeserializer deserializer,
  );

  @protected
  AirBoardContext sse_decode_air_board_context(SseDeserializer deserializer);

  @protected
  AirBoardStroke sse_decode_air_board_stroke(SseDeserializer deserializer);

  @protected
  AirBoardStrokePoint sse_decode_air_board_stroke_point(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AirBoardActivitySummary sse_decode_box_autoadd_air_board_activity_summary(
    SseDeserializer deserializer,
  );

  @protected
  AirBoardContext sse_decode_box_autoadd_air_board_context(
    SseDeserializer deserializer,
  );

  @protected
  ExamBehaviourContext sse_decode_box_autoadd_exam_behaviour_context(
    SseDeserializer deserializer,
  );

  @protected
  EyeRegionSignal sse_decode_box_autoadd_eye_region_signal(
    SseDeserializer deserializer,
  );

  @protected
  GazeCalibrationProfile sse_decode_box_autoadd_gaze_calibration_profile(
    SseDeserializer deserializer,
  );

  @protected
  GazeHeadPoseDecision sse_decode_box_autoadd_gaze_head_pose_decision(
    SseDeserializer deserializer,
  );

  @protected
  HandAirBoardContext sse_decode_box_autoadd_hand_air_board_context(
    SseDeserializer deserializer,
  );

  @protected
  HandGestureInput sse_decode_box_autoadd_hand_gesture_input(
    SseDeserializer deserializer,
  );

  @protected
  HandVisionZones sse_decode_box_autoadd_hand_vision_zones(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  NativeAudioIntelligenceResult
  sse_decode_box_autoadd_native_audio_intelligence_result(
    SseDeserializer deserializer,
  );

  @protected
  EnvironmentFrameDecision sse_decode_environment_frame_decision(
    SseDeserializer deserializer,
  );

  @protected
  ExamBehaviourContext sse_decode_exam_behaviour_context(
    SseDeserializer deserializer,
  );

  @protected
  ExamBehaviourDecision sse_decode_exam_behaviour_decision(
    SseDeserializer deserializer,
  );

  @protected
  EyeIntelligenceResult sse_decode_eye_intelligence_result(
    SseDeserializer deserializer,
  );

  @protected
  EyeRegionSignal sse_decode_eye_region_signal(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FaceAnalysisDecision sse_decode_face_analysis_decision(
    SseDeserializer deserializer,
  );

  @protected
  FaceTemplateStatus sse_decode_face_template_status(
    SseDeserializer deserializer,
  );

  @protected
  FaceVerificationResult sse_decode_face_verification_result(
    SseDeserializer deserializer,
  );

  @protected
  GazeCalibrationProfile sse_decode_gaze_calibration_profile(
    SseDeserializer deserializer,
  );

  @protected
  GazeCalibrationSample sse_decode_gaze_calibration_sample(
    SseDeserializer deserializer,
  );

  @protected
  GazeHeadPoseDecision sse_decode_gaze_head_pose_decision(
    SseDeserializer deserializer,
  );

  @protected
  GazeZonePrediction sse_decode_gaze_zone_prediction(
    SseDeserializer deserializer,
  );

  @protected
  HandAirBoardContext sse_decode_hand_air_board_context(
    SseDeserializer deserializer,
  );

  @protected
  HandAirBoardDecision sse_decode_hand_air_board_decision(
    SseDeserializer deserializer,
  );

  @protected
  HandGestureInput sse_decode_hand_gesture_input(SseDeserializer deserializer);

  @protected
  HandGestureResult sse_decode_hand_gesture_result(
    SseDeserializer deserializer,
  );

  @protected
  HandLandmarkInferenceResult sse_decode_hand_landmark_inference_result(
    SseDeserializer deserializer,
  );

  @protected
  HandLandmarkModelStatus sse_decode_hand_landmark_model_status(
    SseDeserializer deserializer,
  );

  @protected
  HandLandmarkPoint sse_decode_hand_landmark_point(
    SseDeserializer deserializer,
  );

  @protected
  HandRegionSignal sse_decode_hand_region_signal(SseDeserializer deserializer);

  @protected
  HandVisionModelStatus sse_decode_hand_vision_model_status(
    SseDeserializer deserializer,
  );

  @protected
  HandVisionResult sse_decode_hand_vision_result(SseDeserializer deserializer);

  @protected
  HandVisionZones sse_decode_hand_vision_zones(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AirBoardStroke> sse_decode_list_air_board_stroke(
    SseDeserializer deserializer,
  );

  @protected
  List<AirBoardStrokePoint> sse_decode_list_air_board_stroke_point(
    SseDeserializer deserializer,
  );

  @protected
  List<GazeCalibrationSample> sse_decode_list_gaze_calibration_sample(
    SseDeserializer deserializer,
  );

  @protected
  List<HandLandmarkPoint> sse_decode_list_hand_landmark_point(
    SseDeserializer deserializer,
  );

  @protected
  List<Float32List> sse_decode_list_list_prim_f_32_strict(
    SseDeserializer deserializer,
  );

  @protected
  List<NativeLockdownFinding> sse_decode_list_native_lockdown_finding(
    SseDeserializer deserializer,
  );

  @protected
  List<NativeVisionDetection> sse_decode_list_native_vision_detection(
    SseDeserializer deserializer,
  );

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MotionAnalysisDecision sse_decode_motion_analysis_decision(
    SseDeserializer deserializer,
  );

  @protected
  NativeAttemptRecoveryCheck sse_decode_native_attempt_recovery_check(
    SseDeserializer deserializer,
  );

  @protected
  NativeAudioIntelligenceResult sse_decode_native_audio_intelligence_result(
    SseDeserializer deserializer,
  );

  @protected
  NativeHeadPoseReviewResult sse_decode_native_head_pose_review_result(
    SseDeserializer deserializer,
  );

  @protected
  NativeLockdownFinding sse_decode_native_lockdown_finding(
    SseDeserializer deserializer,
  );

  @protected
  NativeObjectReviewResult sse_decode_native_object_review_result(
    SseDeserializer deserializer,
  );

  @protected
  NativeSecureLockdownReviewResult
  sse_decode_native_secure_lockdown_review_result(SseDeserializer deserializer);

  @protected
  NativeSystemSecurityReviewResult
  sse_decode_native_system_security_review_result(SseDeserializer deserializer);

  @protected
  NativeVisionDetection sse_decode_native_vision_detection(
    SseDeserializer deserializer,
  );

  @protected
  NativeVisionFrameQuality sse_decode_native_vision_frame_quality(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  GazeHeadPoseDecision? sse_decode_opt_box_autoadd_gaze_head_pose_decision(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  NativeAudioIntelligenceResult?
  sse_decode_opt_box_autoadd_native_audio_intelligence_result(
    SseDeserializer deserializer,
  );

  @protected
  RotationAnalysisDecision sse_decode_rotation_analysis_decision(
    SseDeserializer deserializer,
  );

  @protected
  ScanFrameDecision sse_decode_scan_frame_decision(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VisionModelStatus sse_decode_vision_model_status(
    SseDeserializer deserializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_acoustic_analysis_decision(
    AcousticAnalysisDecision self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_acoustic_sample_decision(
    AcousticSampleDecision self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ai_action_authorization(
    AiActionAuthorization self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_air_board_activity_summary(
    AirBoardActivitySummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_air_board_context(
    AirBoardContext self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_air_board_stroke(
    AirBoardStroke self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_air_board_stroke_point(
    AirBoardStrokePoint self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_air_board_activity_summary(
    AirBoardActivitySummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_air_board_context(
    AirBoardContext self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_exam_behaviour_context(
    ExamBehaviourContext self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_eye_region_signal(
    EyeRegionSignal self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_gaze_calibration_profile(
    GazeCalibrationProfile self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_gaze_head_pose_decision(
    GazeHeadPoseDecision self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_hand_air_board_context(
    HandAirBoardContext self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_hand_gesture_input(
    HandGestureInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_hand_vision_zones(
    HandVisionZones self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_native_audio_intelligence_result(
    NativeAudioIntelligenceResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_environment_frame_decision(
    EnvironmentFrameDecision self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_exam_behaviour_context(
    ExamBehaviourContext self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_exam_behaviour_decision(
    ExamBehaviourDecision self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_eye_intelligence_result(
    EyeIntelligenceResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_eye_region_signal(
    EyeRegionSignal self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_face_analysis_decision(
    FaceAnalysisDecision self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_face_template_status(
    FaceTemplateStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_face_verification_result(
    FaceVerificationResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_gaze_calibration_profile(
    GazeCalibrationProfile self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_gaze_calibration_sample(
    GazeCalibrationSample self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_gaze_head_pose_decision(
    GazeHeadPoseDecision self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_gaze_zone_prediction(
    GazeZonePrediction self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_hand_air_board_context(
    HandAirBoardContext self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_hand_air_board_decision(
    HandAirBoardDecision self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_hand_gesture_input(
    HandGestureInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_hand_gesture_result(
    HandGestureResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_hand_landmark_inference_result(
    HandLandmarkInferenceResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_hand_landmark_model_status(
    HandLandmarkModelStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_hand_landmark_point(
    HandLandmarkPoint self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_hand_region_signal(
    HandRegionSignal self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_hand_vision_model_status(
    HandVisionModelStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_hand_vision_result(
    HandVisionResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_hand_vision_zones(
    HandVisionZones self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_air_board_stroke(
    List<AirBoardStroke> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_air_board_stroke_point(
    List<AirBoardStrokePoint> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_gaze_calibration_sample(
    List<GazeCalibrationSample> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_hand_landmark_point(
    List<HandLandmarkPoint> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_prim_f_32_strict(
    List<Float32List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_native_lockdown_finding(
    List<NativeLockdownFinding> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_native_vision_detection(
    List<NativeVisionDetection> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_loose(
    List<double> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_motion_analysis_decision(
    MotionAnalysisDecision self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_attempt_recovery_check(
    NativeAttemptRecoveryCheck self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_audio_intelligence_result(
    NativeAudioIntelligenceResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_head_pose_review_result(
    NativeHeadPoseReviewResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_lockdown_finding(
    NativeLockdownFinding self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_object_review_result(
    NativeObjectReviewResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_secure_lockdown_review_result(
    NativeSecureLockdownReviewResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_system_security_review_result(
    NativeSystemSecurityReviewResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_vision_detection(
    NativeVisionDetection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_native_vision_frame_quality(
    NativeVisionFrameQuality self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_gaze_head_pose_decision(
    GazeHeadPoseDecision? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_native_audio_intelligence_result(
    NativeAudioIntelligenceResult? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_rotation_analysis_decision(
    RotationAnalysisDecision self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_scan_frame_decision(
    ScanFrameDecision self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_vision_model_status(
    VisionModelStatus self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class BrainCoreApiWire implements BaseWire {
  BrainCoreApiWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external BrainCoreApiWasmModule get wasmModule;

@JS()
@anonymous
extension type BrainCoreApiWasmModule._(JSObject _) implements JSObject {}
